### ISSUE TITLE
RazorGenerator.MsBuild ignores [project name].wpp.targets

### ISSUE THREAD

**Issue by salarcode** [RazorGenerator/RazorGenerator#102]
It would be really great if 'RazorGenerator' could follow the rules to exclude files from being compiled as described in "[project name].wpp.targets"
The file is described here:
http://www.asp.net/web-forms/overview/deployment/advanced-enterprise-web-deployment/excluding-files-and-folders-from-deployment

"[project name].wpp.targets" is essential for us to have different outputs of the project.

Thanks.

**Comment by pranavkm** [comment]
@salarcode - you're free to specify an `ItemGroup` named `RazorCsSrcFiles` in your primary project \ target file to specify the list of Razor files to compile. The RazorGenerator.MsBuild.targets file will use this value to determine what cshtml files to compile.

**Comment by salarcode** [comment]
The problem is I want to exclude some specific files in different targets, not include them.
I have 500+ views and it makes sense to use "[project name].wpp.targets" which provides exclude feature.

**Comment by salarcode** [comment]
Any word on this?

**Comment by pranavkm** [comment]
Sorry, we're not planning on adding support for this out of the box.
