### ISSUE TITLE
Edit precompiled views for mark up.

### ISSUE THREAD

**Issue by developer9969** [RazorGenerator/RazorGenerator#106]
hi,
wondering if possible ,We create vanilla websites and the clients usually edit the cshtml file and do whatever the like with it.

Is it there a way to do that once a "module/project" that has been precompiled can have it's views edited?

many thanks

**Comment by davidebbo** [comment]
You can set the `UsePhysicalViewsIfNewer` flag t oachieve that. See https://github.com/RazorGenerator/RazorGenerator/wiki/Using-RazorGenerator.Mvc.
