### ISSUE TITLE
How to use RazorGenerator tool in asp.net core webapplication?

### ISSUE THREAD

**Issue by xiaolu6t** [RazorGenerator/RazorGenerator#110]
I can't find custom tool option in file property panel.

**Comment by davidebbo** [comment]
Did you install the RazorGenerator Visual Studio Extension?

**Comment by xiaolu6t** [comment]
I can use it in winform,console and webapplication project.but i can't use it in asp.net core 1.0.

**Comment by davidebbo** [comment]
It does not support core. Please see #19.
