### ISSUE TITLE
Rendering Nested PartialViews

### ISSUE THREAD

**Issue by davidlaughlin** [RazorGenerator/RazorGenerator#113]
I am trying to build a library which contains partial views with additional partial views nested within them.  In my unit tests calling `view.RenderAsHtml(model)` results in `<partial></partial>` to be inserted where the nested partial views should be occurring. Is there a way to have the RazorGenerator descend into the nested views and render them in the html result?

**Comment by pranavkm** [comment]
The actual implementation for rendering partials is buried inside Mvc's view engine which is difficult to setup correctly without being hosted. We settled on rendering a marker to avoid duplicating all of that code in test code.

**Comment by davidlaughlin** [comment]
Understood. Thanks for the feedback.
