### ISSUE TITLE
[Feature request] Open-generic view types with full support for composition.

### ISSUE THREAD

**Issue by Jehoel** [RazorGenerator/RazorGenerator#116]
I would love for there a way for me to have open generic type views which would allow me to compose them such that they can be compiled with strict type safety.

In my own projects, I extend `WebViewPage<TViewModel>` with a subclass `WebViewPage2<TViewModel,TViewData>` that allows for not only a strongly-typed view-model class, but also a strongly-typed `ViewData` subclass.

This system works great for simple views, however it breaks down if you have shared views:

Shared views (e.g. layouts and editor-templates) must specify their `ViewData` by interface, not by concrete class name because shared-views do not exist as open-generic types, and they're referenced by magic-strings (e.g. the `Layout` property with a string path, and the `EditorFor` or `RenderPartial` methods which expect a string name).

I'd love to be able to do something like this:
## MyView.cshtml

(My "entrypoint" view is normal without any special definition, except it doesn't use magic-strings anymore)

```
@inherits WebViewPage2<MyViewModel,MyViewData>
@{
    this.Layout = new MyViewLayout<MyViewModel,MyViewData>();
}
<p>Wubba Lubba Dub Dub</p>
<p>@Html.RenderPartial( new MyPartial<MyViewData>( model: this.Model.Special ), this.ViewData )</p> // passes the current viewdata in verbatim, accessed via MyPartial's `this.ViewData`.
```
## MyViewLayout.cshtml

(I propose the directive `@view` to specify a specific type name and open generic parameters:

```
@view MyViewLayout<TViewModel,TViewData> where TViewData : MyProjectCommonViewData<TViewModel>
@inherits WebViewPage2<TViewModel,TViewData>
<html>
<body>@renderBody()</body>
</html>
```
## MyPartial.cshtml

(This partial requires a specific ViewModel type)

```
@view MyPartial<TViewData> where TViewData : MyPartialViewData
@inherits WebViewPage2<MyPartialViewModel,MyPartialViewData>
<p>@Html.TextBoxFor( m => m.Foo )</p>
```

Is this something RazorGenerator can build independently of the Razor engine?

**Comment by pranavkm** [comment]
This looks like a new directive which requires a change in the Razor parser. We simply wrap the output of the Razor parser \ code generator. 

http://aspnetwebstack.codeplex.com/ would be the place to file work items for the 3.0 Razor parser. That said, it's currently in maintenance with new feature work going towards the AspNetCore Razor parser, so it's unlikely that you would see this being implemented for Mvc 5 or lower.
