### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by MrGorki** [RazorGenerator/RazorGenerator#117]
I am using both Extension and also MVC package but want to uninstall them from project. How to achieve this? Is removing the packages enough? (Because regenerated files are still there)

**Comment by davidebbo** [comment]
Try running `Disable-RazorGenerator` from the Package Manager Console. Or you can manually remove the 'Custom Tool' under the properties for each cshtml view.

**Comment by Worthy7** [comment]
Can I add that the `Disable-RazorGenerator` script is broken right now. 

Exception calling "GetItem" with "1" argument(s): "Value does not fall within t
he expected range."At C:\MYPROJECT\packages\RazorGenerator.Mvc.
2.4.9\tools\RazorGenerator.psm1:63 char:21
+                     $solutionExplorer.GetItem("$SolutionName\$ProjectName$rel
ati ...

**Comment by pranavkm** [comment]
@Worthy7  - that line of code was replaced as part of https://github.com/RazorGenerator/RazorGenerator/pull/139/files#diff-76c22d5383682b643050d95795c8011cL63. Could you try updating the vsix and check if it addresses your issue?

**Comment by Worthy7** [comment]
Yep, I saw your post, thanks. I can't test it right now, but I can reclose this.
