### ISSUE TITLE
RazorGenerator Extension uses hardcoded "SolutionName\ProjectName" path - causes exceptions when project is in a solution folder

### ISSUE THREAD

**Issue by Jehoel** [RazorGenerator/RazorGenerator#121]
This is a reposting of http://razorgenerator.codeplex.com/workitem/116 - because I'm experiencing the same issue.

My solution has an ASP.NET MVC project within a virtual solution folder while the `.csproj` itself is under another directory.

So my Solution Explorer tree view looks like this:

```
+ "FooBar" (Solution node)
    + "Lorem Ipsum" (Solution folder)
        + "Qux" (ASP.NET Project)
            + View.cshtml
```

While my filesystem tree is this:

```
/foobar.sln
    baz/
        qux/
            qux.csproj
            View.cshtml
```

When I run `Enable-RazorGenerator` for the first time in the Package Manager Console I get this exception message repeated for each `*.cshtml` file in the project:

> PM> Enable-RazorGenerator
> Exception calling "GetItem" with "1" argument(s): "Value does not fall within the expected range."
> At C:\foobar\packages\RazorGenerator.Mvc.2.4.7\tools\RazorGenerator.psm1:63 char:21
> 
> <pre>+ ...             $solutionExplorer.GetItem("$SolutionName\$ProjectName$rel ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> + FullyQualifiedErrorId : ArgumentException</pre>

The bug is indeed here: https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Powershell/RazorGenerator.psm1 on line 63:

```
$solutionExplorer.GetItem("$SolutionName\$ProjectName$relativePath").UIHierarchyItems.Expanded = $false
```

`$solutionExplorer.GetItem` corresponds to `EnvDTE.UIHierarchy.GetItem(String names)` which requires a "tree path" as opposed to a filesystem path, however computing that path is complicated. I suspect a better approach might be to instead iterate through the UIHierarchy and then set its collapsed state if it's a `*.cshtml` file instead of using the same file-list from `Get-ProjectFiles`.

**Comment by Worthy7** [comment]
Bump.

**Comment by foresightyj** [comment]
I experienced the same error. Wish this bug can be fixed soon.

**Comment by salarcode** [comment]
Bump x2

**Comment by Jehoel** [comment]
I've made a fix for this issue and added a pull-request: https://github.com/RazorGenerator/RazorGenerator/pull/139

**Comment by pranavkm** [comment]
Thanks @Jehoel - could the rest of you try out the vsix that includes @Jehoel's change - http://razorgen-ci.cloudapp.net/viewLog.html?buildId=173&buildTypeId=RazorGenerator_RazorGenerator&tab=artifacts and let us know if the issue is addressed?
