### ISSUE TITLE
Razor Generator extension breaking .cshtml files

### ISSUE THREAD

**Issue by 96fauj** [RazorGenerator/RazorGenerator#122]
I've reinstalled Razor Generator in visual studio 2015 enterprise and now I can't open .cshtml files. The previously generated templates are still an old version. 

So when I disable the extension, I can now open the .cshtml files and I delete the old generated templates so that they don't keep overwriting my new .cshtml pages.

**Comment by davidebbo** [comment]
Not sure I quite follow. Is the problem that you can't open .cshtml, or that the extension is overwriting your .cshtml files? I have not seen either behavior.

**Comment by 96fauj** [comment]
The extension makes the .cshmtl files unavailable. The error message (ill
update the post with the exagt one) is somewhere along the lines of "this
file has moved or is inaccesible". This is both when debugging and without.

**Comment by 96fauj** [comment]
Exagt error that I'm receiving when I enable the Razor generator extension installed in VS 2015.
http://i.imgur.com/TFQIkms.png

**Comment by 96fauj** [comment]
@davidebbo 
Update: I've just come across another possibly unrelated issue with my views in a class library. They no longer have access to the Html helpers and the error I'm getting is that Html does not exist in the current context. Any ideas why this might have happened? Almost feels like it's some sort of web.config issue but we can't seem to figure this out.

**Comment by davidebbo** [comment]
I've never seen that, but I'm going to venture that you have some issues in your installation that goes beyond RG.

**Comment by 96fauj** [comment]
@davidebbo We're trying to have a class library with views that can be shared over to a web project as written in your description. We've looked over your example and in their you seem to have 2 web projects however in the description and as we're attempting it we're using a class library.

**Comment by davidebbo** [comment]
Not sure I follow. If you run my test solution (https://github.com/davidebbo-test/RazorGeneratorMvc51) unmodified, does everything work for you?

**Comment by 96fauj** [comment]
Hmm, my issue isn't with Razor generator currently I think. It was with us not being able to have views in a class library and have the razor intellisense work.

**Comment by davidebbo** [comment]
I see. Closing here, then. For general Razor issues, can you try the MSDN forum? This repo is only about RazorGenerator.
