### ISSUE TITLE
RazorGenerator.MsBuild and Refactor-rename

### ISSUE THREAD

**Issue by amura11** [RazorGenerator/RazorGenerator#124]
I followed [this](https://stacktoheap.com/blog/2013/01/19/precompiling-razor-views-in-asp-dot-net-mvc-3/) guide to setup my project with RazorGenerator and everything seems to be working fine with the exception of refactoring. When I refactor-rename a property in a view model and build I get no errors (not what I expect) but if I open a cshtml that references the renamed field it shows an error (which is expected). If I do a clean and then a build I still get no errors. The only way I can get the error to show up when I build is to delete the "CodeGen" folder and build.

My guess as to what's happening is that when I refactor-rename a property the generated cs files get refactored as well but the cshtlm is not (which is normal). This is problematic because the cshtlm is invalid but no errors are given until I manually delete the CodeGen folder.

**Comment by davidebbo** [comment]
Having refactor work directly on the cshtml file would require magic way beyond what RG can do!

All RG does is turn the cshtml into a .cs file. Beyond that, VS just does what it does.

**Comment by amura11** [comment]
Thanks @davidebbo! I should have been more clear though, of course I don't expect RG to refactor my cshtml files, that would be absurd haha

Is there a way to configure RG to always regenerate cshtml files or a way to set VS so it ignores the generated cs files when it does the refactor?

The only way I could make this work right now was to have MSBuild delete the CodeGen folder before build so that the files get generated. It works but it feels like a bit of a hack.

**Comment by pranavkm** [comment]
@amura11 - perhaps adding compile files as parameters to our target's incremental build evaluation (https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.MsBuild/RazorGenerator.MsBuild.targets#L39) might do the trick.

**Comment by davidebbo** [comment]
Note that there is an msbuild way of using RG that works at build time and may be more what you need. See https://github.com/RazorGenerator/RazorGenerator/wiki/Using-RazorGenerator.MsBuild.

I doubt there is a way to make VS run the custom tool at refactor time, or to stop it from refactoring codegen'ed files.
