### ISSUE TITLE
RazorGenerator.MsBuild generated cs files have incorrect files paths in #line

### ISSUE THREAD

**Issue by amura11** [RazorGenerator/RazorGenerator#125]
I followed [this](https://stacktoheap.com/blog/2013/01/19/precompiling-razor-views-in-asp-dot-net-mvc-3/) guide and when I have compile errors the file paths in the `#line` are incorrect. The path is a relative to the source cshtlm from the cshtml file not the generated cs file.

Eg.
`#line 6 "..\..\Views\Shared\myView.cshtml"` (the relative path to the cshtml file from the cshtml's location) where as it should actually be `#line 6 "..\..\..\..\Views\Shared\myView.cshtml"` (the relative path to the cshtml from the generated cs file's path)

Although minor, this means that doubling clicking the error in Visual Studio doesn't open the file and jump to the correct line.

**Comment by davidebbo** [comment]
Try `@* GenerateAbsolutePathLinePragmas: true *@`.  See https://github.com/RazorGenerator/RazorGenerator#special-razor-directives
