### ISSUE TITLE
VS 2017 compatibility

### ISSUE THREAD

**Issue by hyp4** [RazorGenerator/RazorGenerator#127]
Any chances for an update to make the extension compatible with VS 2017 please? Having a RC out seems to be a good point to do so if possible.

**Comment by robichaud** [comment]
Any idea when this will be released?

**Comment by davidebbo** [comment]
This is tracked by #131.

**Comment by davidebbo** [comment]
If you care about this issue, please make sure to head over to that other issue to help validate @pranavkm's build.

**Comment by davidebbo** [comment]
VS 2017 support is now in.
