### ISSUE TITLE
Partial Views with dynamic contents don't render

### ISSUE THREAD

**Issue by ibenyaminhanna** [RazorGenerator/RazorGenerator#128]
I have the following view which consists of 3 partial views, two of them need to be passed an object as their model.

/*************************************************************************************************
@model sitemap

< header id="hoccmn-header" data-spy="affix" data-offset-top="30" class="hoccmn" >

  @{Html.RenderPartial("widgets/Header/Skipbar/_Skipnav"); }
    @{Html.RenderPartial("widgets/Header/Toolbar/_Tools-bar", thisModel.toolbar); }
    @{Html.RenderPartial("widgets/Header/Navbar/_Nav-bar", thisModel.navbar);}

 < /header > 

CS generated code is

public partial class _Views_Shared_widgets__Header__Header_cshtml : System.Web.Mvc.WebViewPage<sitemap>
    {
        public _Views_Shared_widgets__Header__Header_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
  
    sitemap appSitemap = null;

    if (Model == null)
    {

        string siteMapPath = "E:/WorkspacesHoC/HoC/Web/Projects/HOCWB/WebApps/HocCommonElements/HocCommoneElementsViewsLibrary/App_Data/SiteMap.xml";

        System.Xml.Serialization.XmlSerializer ser = new System.Xml.Serialization.XmlSerializer(typeof(sitemap));
        FileStream file = new FileStream(siteMapPath, FileMode.Open);
        appSitemap = (sitemap)ser.Deserialize(file) as sitemap;
        file.Close();
    }

    var thisModel = (Model != null) ? Model : appSitemap;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<header");

WriteLiteral(" id=\"hoccmn-header\"");

WriteLiteral(" data-spy=\"affix\"");

WriteLiteral(" data-offset-top=\"30\"");

WriteLiteral(" class=\"hoccmn\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
      Html.RenderPartial("widgets/Header/Skipbar/_Skipnav"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 25 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
      Html.RenderPartial("widgets/Header/Toolbar/_Tools-bar", thisModel.toolbar); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 27 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Shared\widgets\_Header\_Header.cshtml"
      Html.RenderPartial("widgets/Header/Navbar/_Nav-bar", thisModel.navbar);
            
            #line default
            #line hidden
WriteLiteral("\r\n</header>");

        }
    }
}

        }
    }
}
**************************************************************************************************/
The problem is:-
 in my test code, when I do
var view = new _Views_Shared_widgets__Header__Header_cshtml();
string output = view.Render();

output sting does not have the generated partial views, instead it has a < placeholder>GUID< /placeholder>  for each one of the three partial views (below).

is there any way to het the three partial views to render so I can have their Markup HTML?
/**************************************************************************************************
< header id="hoccmn-header" data-spy="affix" data-offset-top="30" class="hoccmn" >
    < placeholder>a3b7048b-14a9-4007-b927-f18f8425459a</placeholder>

    
< placeholder>d0a08b90-2731-4b1f-8d0f-0de68488a852</ placeholder >

  < placeholder>5f6fdacf-a41d-4649-bd33-ba2f16b14e9a</ placeholder >
    
< /header>
**************************************************************************************************/

**Comment by pranavkm** [comment]
Locating partial views is part of the Mvc viewengine. Unfortunately simulating it's behavior in the test code isn't trivial and hard to get correct. If you'd like to verify a fully rendered view, I'd recommend using something like http://blog.stevensanderson.com/2009/06/11/integration-testing-your-aspnet-mvc-application/ that allows E2E testing.
