### ISSUE TITLE
Can I register view engines in Application_Start rather than using WebActivatorEx?

### ISSUE THREAD

**Issue by migig** [RazorGenerator/RazorGenerator#13]
The nuget automatically creates a class which calls `WebActivatorEx.PostApplicationStartMethod`.

Problem is we perform all our init work in one place (called from `global.asax`'s `Application_Start`), and all our tests are wired that way too. The automatic/magic webactivator approach is awesome, but doesn't play nice in our design.

So, *is it safe for me to register the view engines in `Application_Start`?*

Is this too early or too late in the startup pipeline? Seems to me Application_Start occurs before WebActivatorEx, so wondering if its ok? It seems to work, but I want to make sure I'm not going to break something.

**Comment by davidebbo** [comment]
I think doing it in `Application_Start` is fine.

**Comment by davidebbo** [comment]
Closing. Let us know if you have further questions.

**Comment by migig** [comment]
Thanks :smile:
