### ISSUE TITLE
Doesn't support VS 15 (VS 2017)

### ISSUE THREAD

**Issue by benbenwilde** [RazorGenerator/RazorGenerator#131]

**Comment by davidebbo** [comment]
I was hoping it would be as easy easy as making this change: https://github.com/RazorGenerator/RazorGenerator/commit/89a245337b7ae79d9330e9e639ce9429ace9d2ce.

But when I try to upload the resulting VSIX (from CI) to VS gallery, it complains:

> This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK. Please make sure to update your references and try uploading again. Note: you'll also need to add Prerequisites to your extension.vsixmanifest.

So seems we need to upgrade SDKs and do other fancier things. @pranavkm I'm hoping you know the drill from having done previous versions :)

**Comment by pranavkm** [comment]
I've been working on a different VSIX for VS 2017 and we had to install a SDK (that conveniently is distributed as a package). Perhaps we need to do something similar here. I'll give this a try over the weekend.

**Comment by pranavkm** [comment]
Could you give the vsix at http://razorgen-ci.cloudapp.net/repository/download/RazorGenerator_RazorGenerator/167:id/RazorGenerator.vsix a try?

**Comment by ManfredLange** [comment]
@pranavkm I tried that vsix and it installs. However, in the ASP.NET Core MVC 1.1 project I can't find the place where to tell a view or partial to use a custom tool. The property pages for views and partials in that type of project look different to those in ASP.NET MVC 5.

What am I overlooking?

**Comment by davidebbo** [comment]
@ManfredLange RazorGenerator does not support ASP.NET Core (see #19). That is a different topic from this issue, which is about VS 2017 support (for the same scenarios supported in VS 2015).

**Comment by davidebbo** [comment]
So @pranavkm, it sounds like you had done that work and was only waiting for confirmation from people that it works?

Ignoring the unrelated Core limitation, it doesn't look like anyone has tried it.

**Comment by pranavkm** [comment]
Yup - I wanted to get some confirmation from the wild before publishing the vsix. We've had issues in the past where things work on my box ™️ but tend to fail on other people's machines

**Comment by luminalpark** [comment]
@pranavkm I'm using it actually on VS2017 and seems to work perfectly.

**Comment by pranavkm** [comment]
@davidebbo would you be able to publish the vsix?

**Comment by davidebbo** [comment]
@pranavkm one thing that seems strange: I installed it on both 2015 and 2017. After doing this, in 2015, I ended up with two versions side by side: the 1.10.1 that I already had, and your new 1.12.2:

![image](https://cloud.githubusercontent.com/assets/556238/22939682/626addf4-f294-11e6-8248-e869bde6a3b0.png)

That makes me think that somehow, the manifest changes caused it to lose its identity and become a new different extension, which could be problematic.

Looking at [this](https://github.com/RazorGenerator/RazorGenerator/blob/ae56bc6516f452be8b1436bd74f46b67609c74e7/RazorGenerator.Tooling/source.extension.vsixmanifest#L4), the `Id="RazorGenerator..2FD58EB3-29A2-40A3-BE17-C024CA9A17A2"` part looks a bit funky. Is that really supposed to have both the name and the Id in a single attribute?

**Comment by davidebbo** [comment]
Looking at https://msdn.microsoft.com/en-us/library/hh696828.aspx, the Id should be just the Guid. I'm pretty sure that's the problem.

As an aside, any reason to jump from 1.10.x to 1.12x instead of 1.11? :)

**Comment by pranavkm** [comment]
> As an aside, any reason to jump from 1.10.x to 1.12x instead of 1.11? :)

Nope. I think that might have been accidental. 

I stole the ID thing from the other vsix. I guess I have two places to fix it now 😄

**Comment by pranavkm** [comment]
https://github.com/RazorGenerator/RazorGenerator/pull/136

**Comment by davidebbo** [comment]
Ok, 1.11 is released to the VS gallery!
