### ISSUE TITLE
Editing capabilities

### ISSUE THREAD

**Issue by vyelchuri** [RazorGenerator/RazorGenerator#138]
There is any EASY editing capability to achieve through this. editing the razor template and click refresh on the browser to see the reflected changes  !!

**Comment by davidebbo** [comment]
Yes, that is indeed how it works.

**Comment by vyelchuri** [comment]
@davidebbo I created all my razor views in the class library and hooked up to MVC web application, it successfully worked. If i would like to change the razor template which is on class library on the fly when it is running and see the reflected the change in the browser is my issue. Is that possible or not ?

**Comment by davidebbo** [comment]
Sorry, it sounded like you were just making a statement that things were working, and not asking a question.

You should look at the `UsePhysicalViewsIfNewer` flag.

**Comment by pranavkm** [comment]
> I created all my razor views in the class library and hooked up to MVC web application

That usually wouldn't work. The precompiled view engine looks at the current application's views directory (it has no idea where the class library came from). So it's quite likely you wouldn't be able to make refresh work with `UsePhysicalViewsIfNewer`

**Comment by vyelchuri** [comment]
@pranavkm there is any way to work providing refresh option with out rebuilding the class libraries ??

**Comment by pranavkm** [comment]
You could register a view engine ahead of the precompiled one and do what we do but pointing at the class library. See relevant pieces of code here: https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Mvc/PrecompiledMvcEngine.cs#L146.

**Comment by vyelchuri** [comment]
@pranavkm @davidebbo I have created sample application  https://github.com/vyelchuri/PrecompiledViewsTest 
I ran the application when it is debug mode. i have changed the content of About.cshtml when i hit refresh it was not working. Sorry if my english is bad
