### ISSUE TITLE
BaseType does not support generic arguments

### ISSUE THREAD

**Issue by onionhammer** [RazorGenerator/RazorGenerator#142]
Setting BaseType to something with a generic arg, the generic argument is stripped out when the code is generated

**Comment by onionhammer** [comment]
Workaround:

use `@inherits MyBaseType<MyGenericArg>`

**Comment by Jehoel** [comment]
I think this issue should be re-opened as it's either a bug or a bad design. I'd appreciate some clarity and guidance from the RazorGenerator team. Why does the `BaseType` directive even exist if we already have `@inherits`? (I understand for the `*.directives` files, but couldn't they prohibit the `BaseType` directive from being used in individual `.cshtml` files - or fix `BaseType` to support generics and then prohibit the `@inherits` Razor directive?
