### ISSUE TITLE
Changing Branches....

### ISSUE THREAD

**Issue by Worthy7** [RazorGenerator/RazorGenerator#144]
Hello there, 

At the moment a single file view is regenerated if a user saves the corresponding cshtml file.
I know we have .msbuild, but it regenerates all files at compile time (which takes time)

Could we not have a kind of hybrid checker at compile time:
```
At compile time, for each cshtml file
    If no corresponding generated.cs file:
        Generate it()
    else if there is a corresponding generated.cs file AND it's LastModifiedVersion matches this cshtml file:
        Do nothing
    Else:
        Generate it()
```

This would mean that when a user switches branches, they 1) Don't have to have generated.cs in there repo, and 2) don't have to worry that the generated files won't be up to date with any changes

**Comment by pranavkm** [comment]
We're really not planning on adding build \ compile time tooks in to the vsix. It changes the tool from being a single file generator which is simple to write and manage to a VS component that participates in build that's much more difficult to get right. You could look at what we do in `Redo-RazorGenerator` and wrap it up in extra ps code that does what you're looking for.

**Comment by Worthy7** [comment]
Ok, Could you suggest how I am supposed to be managing this then when changing branches and having generated.cs files?

**Comment by Worthy7** [comment]
Basically this just bloats git. we cannot change branches and have reliable pages built - in fact it's dangerous right? What if we compile, switch branches, and it include the other branches build generated.cs file into the main build for this branch?
I guess for now including the generated.cs file into git is the only solution :-/ 
Or rerun the Redo script every time we change branch...
