### ISSUE TITLE
Bug: MVC + MsBuild

### ISSUE THREAD

**Issue by Worthy7** [RazorGenerator/RazorGenerator#147]
Hello,

I had MSBUILD installed. Removed it.
Installed MVC.
Now it is running both MSBUILD and MVC. I am getting generated.cs files, and also the entire CodeGen folder is being created.
No idea how to fix this, where are hooks for MSBUILD stored? It seems it didn't clean itself properly when I uninstalled it. (No errors though.)

**Comment by svrx** [comment]
The hooks are in your  project file (csproj) as targets. 
RazorGenerator.MSBuild nad RazorGenerator.Mvc serve different purposes.
RG.MSBuild is used to pre-compile your view into an assembly at build time.
RG.Mvc is used to consume those pre-compiled views from the DLL.
