### ISSUE TITLE
RazorGenerator.MSBuild uses outdated versions of System.Web.Mvc and System.Web.Razor 

### ISSUE THREAD

**Issue by svrx** [RazorGenerator/RazorGenerator#148]
I have this issue were a view, that is using specific features of Razor syntax for Mvc, is getting different behaviour when it's compiled at build time by `RazorGenerator.MSBuild` and at runtime by the JIT.

After some investigation I've realized that the difference was originated from the fact that my project uses `System.Web.Razor` with version 3.0.20129.0 , but the RazorGenerator.MSBuild is stuck with version 3.0.11001.0, which is an older one. Since those assemblies are packaged inside your Nuget the flexibility upgrading the version use at the consumer side is not there.

This generates severe inconsistencies and errors in some cases.
Is there any known way of getting around this issue with current package?

I'm available to submit a PR with my suggested fix, please let me know your opinion and if this would be welcome.

**Comment by pranavkm** [comment]
I think updating the package (https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Core.v3/packages.config#L4) in particular if there are parser changes.

**Comment by svrx** [comment]
Yes, if I generate my own packages and maintain those for there on it's an easy option, but not something I'm keen on doing as a first alternative.

Ideally `RazorGenerator.MsBuild` should use exactly the same version of the dependencies used by the project it's being executed on.

I was thinking doing something like:
* Inspect the project file and figure out version and source of those dependencies
** If an hintPath is provided, just used that location
** Else if not available fall back to the pre-package cores and dependency assemblies

Would you be open to review something along those lines?

**Comment by pranavkm** [comment]
@svrx I meant we'd be happy to take a PR with the update. `Microsoft.AspNet.Razor` 3.2.3 has been out for a while so it should be fair to produce a version of our tooling that requires it.

**Comment by svrx** [comment]
@pranavkm, perfect then. 
Will update the whole set of dependencies to the latest.

**Comment by pranavkm** [comment]
Fixed in https://github.com/RazorGenerator/RazorGenerator/commit/032180e4d36638d894f50eabd97bbc68d833d2bc. https://www.nuget.org/packages/RazorGenerator.MsBuild/2.5.0 should have the updated versions.
