### ISSUE TITLE
Switch to ValueTuple

### ISSUE THREAD

**Issue by onionhammer** [RazorGenerator/RazorGenerator#150]
Currently the code generator will generate classic Tuples, but System.ValueTuple adds a struct Tuple type; why not switch to that?

**Comment by pranavkm** [comment]
This would be an issue for the Razor parser (https://github.com/aspnet/aspnetwebstack). That said, the Razor team's working on AspNetCore's implementation of Razor (https://github.com/aspnet/Razor) and it's unlikely they are going to invest in new feature work in the Mvc 5.0 / Razor 3.0 code base.
