### ISSUE TITLE
not generating generated.cs

### ISSUE THREAD

**Issue by WangQiru** [RazorGenerator/RazorGenerator#154]
I'm trying to get the generator running on a console app, following the demo [RazorGeneratorSimpleTemplate](https://github.com/davidebbo-test/RazorGeneratorSimpleTemplate)

The steps I've done:
1. Installed RazorGenerator.Templating 
2. Created TestPage.cshtml (content from the demo app)
```csharp
@* Generator: Template GeneratePrettyNames : true *@

@functions {
    public string Message { get; set; }
}


<ul>
    @for (int i = 0; i < Max; i++)
    {
        <li>Hello @Message</li>
    }
</ul> 
```
3. Changed custom tool to RazorGenerator

However, no generated.cs file is generated as suggested in the guide

> You’ll notice that a nested file is added to your project.

When I tried to modify the content of the demo app, the changes won't reflected in the nested cs file as well. 

Now the only way to get it working, is to install RazorGenerator.MsBuild, and for every change I made to my .cshtml files, I need to restart Visual Studio, thought still not generating .cs files as nested files, they are being generated in obj\CodeGen folder.

**Comment by pranavkm** [comment]
@WangQiru you'll need either the VSIX or the MSBuild file to generate the tool. `RazorGenerator.Templating` provides runtime support for the generated file.

**Comment by WangQiru** [comment]
@pranavkm HI, thanks for the prompt reply. I did install RazorGenerator.MSBuild, but .cs files are still not being generated as suggested.

**Comment by WangQiru** [comment]
@pranavkm are you saying that for console applications, the only solution is to restart for changes?

**Comment by pranavkm** [comment]
Or install the VSIX. That should regenerate the file on change.

**Comment by WangQiru** [comment]
Oh thanks, now I understand.
