### ISSUE TITLE
Missing documentation for using RazorGenerator with views from multiple assemblies

### ISSUE THREAD

**Issue by RudeySH** [RazorGenerator/RazorGenerator#168]
Let's say I have a MVC project which has some views in it's own assembly, but it also references two class libraries (which are actually also MVC projects) that contain their own views. How do I register the view engine properly?

Does each assembly need it's own RazorGeneratorMvcStart? How do I ensure the view engines are added in the correct order? Do I need to start using CompositePrecompiledMvcEngine?

I couldn't find a lot of information on this subject.

**Comment by pranavkm** [comment]
You'd have to use a `CompositePrecompiledMvcViewEngine` if the intent is to have multiple precompiled assemblies. `RazorGeneratorMvcStart` doesn't quite work in this case since it registers multiple vanilla (non-composite) precompiled view engine.

**Comment by RudeySH** [comment]
Alright, I understand how it works now. Feel free to close this issue if you feel like this shouldn't be added to the docs.
