### ISSUE TITLE
Force rebuild *all* generated.cs files

### ISSUE THREAD

**Issue by DianaKoenraadt** [RazorGenerator/RazorGenerator#181]
Hi all,

is it possible to have RazorGenerator forcefully rebuild every single .cshtml file (marked CustomTool=RazorGenerator)? A rebuild of my solution doesn't rebuild the views. Have I missed a setting?

Kind regards,
Diana

**Comment by ensemblebd** [comment]
same problem. I can't get them to recompile at all now. Something has changed and broken the system. This worked before.

**Comment by DianaKoenraadt** [comment]
Found it! 
You can go to the Package Manager Console and enter:

> Redo-RazorGenerator
