### ISSUE TITLE
Invalid Generation from cshtml

### ISSUE THREAD

**Issue by marcelinorui** [RazorGenerator/RazorGenerator#184]
While doing a in a cshtml,

    @using MyViewModel
    <div id="edit_@Model.Uuid"></div>

where `@Model.Uuid` is `System.Guid`

the generated code was:

    WriteLiteral("\r\n<div id=\"edit_@Model.Uuid\"></div>");

Can you guys help me please?

**Comment by Jehoel** [comment]
Razor ignores syntax where the `@` is inside an attribute value with other ambiguous characters.

Try this instead:

    <div id="@( "edit_" + this.Model.Uuid.ToString() )"></div>

**Comment by marcelinorui** [comment]
Tanks.

**Comment by Jehoel** [comment]
Closing this issue then. If you encounter this behavior with the `@( expr )` syntax please file a new issue.
