### ISSUE TITLE
MvcHelper Directive produces uncompilable code

### ISSUE THREAD

**Issue by timramone** [RazorGenerator/RazorGenerator#187]
There is a test template with `Generator: MvcHelper` directive is this repository:
https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Core.Test/TestFiles/Input/MvcHelperTest.cshtml

There also is a generated file from this template with RazorGenerator `v1` here: 
https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Core.Test/TestFiles/Output_v1/MvcHelperTest.txt

We can see that in this file we have a static class with a static extension method, which is compilable and fine.

But in a generated file for RazorGenerator `v2` or `v3` we have nonstatic file with a static extension method: 
https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Core.Test/TestFiles/Output_v2/MvcHelperTest.txt#L37

Unfourtunatedly this code can't be compiled in C#:
```Error CS1106: Extension method must be defined in a non-generic static class```

Static changed to nonstatic in `v2` via this commit: https://github.com/RazorGenerator/RazorGenerator/commit/7052aaae4b580d0e5518a3fe1b85423d2448f094#diff-97f8c72576b159fc6053d5bfc84f6d9e

Can you fix it somehow? I can't regenerate some files in my solution anymore with this new version of RazorGenerator :(

**Comment by timramone** [comment]
@pranavkm do you still work here? Could you please shed some light on this? :)

**Comment by Jehoel** [comment]
I'm actively involved in maintaining this project after being added to the project team by pranavkm, and I'm working through other issues with RazorGenerator at present but I'll take a look at this when I get a chance.

I note that ASP.NET Core dropped support for `@helper` syntax in Razor pages, so your question might be moot if you're targeting the latest version of ASP.NET (not to say this isn't a bug, of course).

**Comment by pranavkm** [comment]
@timramone MVC 4.0 changed how the helper type is generated - in 4.0, the generated type has to derive from a non-static base class. The generated method is still static, so you can continue calling it in a static context, just not as an extension method.

**Comment by timramone** [comment]
So you are saying that this is not a bug and woudn't be fixed? 
But it definitedly breaks backward compatibility, doesn't it?

=(

**Comment by Jehoel** [comment]
As a workaround, you could add a pre-build event script to your project that removes the `this` modifier to the first parameter to allow the code to compile, at least - though doing text find-and-replace inside Windows batch scripts isn't pretty: https://stackoverflow.com/questions/60034/how-can-you-find-and-replace-text-in-a-file-using-the-windows-command-line-envir

**Comment by timramone** [comment]
It's too complicated, I can just rewrite the code.
Thanks anyway.

**Comment by pranavkm** [comment]
> But it definitedly breaks backward compatibility, doesn't it?

Unfortunately the breaking change was in MVC 4. All that RazorGenerator (primarily) does is provide a way to use MVC's runtime capabilities at build time.
