### ISSUE TITLE
Razor Generator support mvc 6

### ISSUE THREAD

**Issue by quantruong** [RazorGenerator/RazorGenerator#19]
Hi David,

Can you tell me Razor Generator support mvc 6? If yes, How can to do that , because I don't see Custom Tool when view properties cshtml view. If no, Can you provide me suggestion to do that? , I will research it.

Thanks,
Quan

**Comment by pranavkm** [comment]
Mvc 6 has support for precompiled views out of the box. There's no plan on adding support for it via RazorGenerator.

**Comment by mcintyre321** [comment]
How will this work with library projects containing views, or will this not be required?

**Comment by pranavkm** [comment]
@mcintyre321, there's still work to be done with precompilation in Mvc6. In the current format, it involves dropping a precompilation module (see https://github.com/aspnet/Mvc/tree/dev/test/WebSites/PrecompilationWebSite) in the project, although that approach is likely to change before it RTMs.

**Comment by nicholaj05** [comment]
"Mvc 6 has support for precompiled views out of the box. There's no plan on adding support for it via RazorGenerator" this is no longer true as it is being removed from MVC 6 RC2 with no plans to re-introduce it for the final version.
See link: https://github.com/aspnet/Mvc/issues/3993
In view of this would it possible to release a new version of RazorGenerator for MVC 6?

**Comment by mcintyre321** [comment]
Also, I don't think that the MVC6 precompile module would let you produce stand-alone Razor based helpers, which is a very useful feature of RazorGenerator.

**Comment by davidebbo** [comment]
MVC6 is a pretty different beast, so adding support is likely a non-trivial thing (if at all possible). For this to happen, someone would need to take on that task and drive it.

But if the model is so different that having a single extension for MVC5 and MVC6 is not feasible, then the best plan might be to start a separate extension that targets the new world of MVC6 and .NET core without carrying the years of baggage that come with the current extension.
