### ISSUE TITLE
IIS (azure cloud service) still compile my views in Temporary ASP.NET files folder

### ISSUE THREAD

**Issue by Korouzan** [RazorGenerator/RazorGenerator#195]
Hello,

I have a webApp MVC 5, I install RazorGenerator.MVC (that create a RazorGeneratorMvcStart on AppStart) and RazorGenerator.MsBuild.
On my build VM, I have the obj/codegen folder.
When I deploy on IIS (cloud service), in my webapp.dll (use ILSpy to decompile the assembly) I have all the precompiled views (views.cs) in ASP folder BUT when I first hit the pages, I still have a very slow rendering due to IIS recompiled the views in Temporary Asp.NET files folder(20 sec).

Is someone have the same issue ?
Thanks

**Comment by Jehoel** [comment]
* Are you still uploading `*.cshtml` files to the server? By default, `*cshtml` files will still be compiled to override any precompiled views. Simply don't upload the `*.cshtml` files to prevent this.
* Is your application still using the RazorGenerator view-engine that will recognise and use the precompiled views? It isn't enough to reference the package or use the MSBuild component, you need to reconfigure ASP.NET to use the different view-engine.

**Comment by Korouzan** [comment]
You are right !
I'll try to remove all my cshtml from the server.
For the view-engine, I use a CustomViewEngine in my global.asax (clear all view engine before calling my CustomViewEngine) so I'll remove it and see if my performance improve.

Thanks a lot

**Comment by Korouzan** [comment]
It works ! Thank you a lot
