### ISSUE TITLE
RazorGenerator.MsBuild 2.3.0 is Broken, Missing MVC 5.0 Assembly in V3 Folder

### ISSUE THREAD

**Issue by sliverninja** [RazorGenerator/RazorGenerator#2]
## Summary
Please [correct the missing assembly issue in the Nuget package](https://razorgenerator.codeplex.com/workitem/163) or [remove the bad package](https://www.nuget.org/packages/RazorGenerator.MsBuild/) - this is wasting people's times. 

If you create a new MVC app in MVC 5, the CodeGen output namespace is always ASP and the assembly namespaces are not added properly from the Views web.config. Please save us all the grief. 

## Issue
The symptoms are very strange. For us - it was complaining about being unable to resolve class references - despite their namespaces being present in `Views\web.config`. 

Once corrected with full namespace path, it would complain: 
>Error 1 Could not precompile the file '\Views\Shared\myviewname.cshtml'. Ensure that a generator declaration exists in the cshtml file. 
A generator declaration is the first line of your cshtml file and looks like this: 
@* Generator: MvcHelper *@
Valid host names: MvcHelper, MvcView, Template, WebPagesHelper, WebPage, RazorGenerator.Core.IHostProvider ..\packages\RazorGenerator.MsBuild.2.3.0\build\RazorGenerator.MsBuild.targets	21	9	My Project

## Workaround
 Here is the workaround - `Install-Package RazorGenerator.MsBuild -Version 2.2.6` OR manually copy the MVC 5 assembly from the previous package or locally (`System.Web.Mvc.dll`) and place it under `\packages\RazorGenerator.MsBuild.2.3.0\tools\v3`

**Comment by davidebbo** [comment]
@pranavkm any idea here? Comparing 2.2.6 and 2.3.0, the one difference is indeed that `System.Web.Mvc.dll` is missing from the v3 folder. In v1/v2, it's there. Some kind of packaging issue?

**Comment by davidebbo** [comment]
For now, I unlisted version 2.3.0 in nuget, until Pranav gets a chance to take a look.

**Comment by sliverninja** [comment]
Awesome - thanks for the quick feedback and resolution David! =)

**Comment by pranavkm** [comment]
Not sure why the file went missing - perhaps something on my dev box was messed up. I'm working on setting up a CI server (http://razorgen-ci.cloudapp.net) plus some test automation to verify we get more consistent releases.

**Comment by sliverninja** [comment]
Ahh...the joys of packaging and deployment! CI is certainly worth the effort so the end result matches the authors intent. =)

Thanks for the extra efforts @pranavkm! Looking forward to the benefits - we couldn't execute our MVC strategy without your Razor precompilation tooling for our shared MVC UI library. =)

Kudos for the updates!

**Comment by radiok** [comment]
I still see this issue with the latest version of RazorGenerator.MsBuild (2.3.5), the tools\v3 folder does not have a System.Web.Mvc.dll.  This isn't a huge problem locally, but my continuous integration server is really choking on this problem, so much so that I've rolled back to version 2.2.6.  Is there any chance this will be resolved soon?  I would do it myself, but I'm having trouble figuring out how the NuGet package is formed from this github.

**Comment by pranavkm** [comment]
I think @davidebbo might not have picked up the package from the CI when he last pushed it. The CI was producing a 2.3.6 package that has a v3\System.Web.Mvc.dll - could you try updating to it?

**Comment by davidebbo** [comment]
Ah yes, my bad. So I see you pushed 2.3.6 to NuGet, which should resolve this.
