### ISSUE TITLE
Web.config break on nuget update

### ISSUE THREAD

**Issue by Erok21** [RazorGenerator/RazorGenerator#20]
I'm using razorgenerator to create a single menu view to go across multiple web apps. It works great...except for one quirk. In updating my redirect bindings in my web.config, it formats them wrong, breaking all of my redirects.

Instead of formatting like the following:

    <runtime>
        <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
        </dependentAssembly>
        <dependentAssembly>
            <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
        </dependentAssembly>
        <dependentAssembly>
            <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
        </dependentAssembly>
    </runtime>

, it is misformatting it, similar to the following:

    <runtime>
        <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
            <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
        </dependentAssembly>
        <dependentAssembly>
            <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
        </dependentAssembly>
    </runtime>

with inconsistent results. Any idea what might be causing this? Or potential solutions?

.Net Framework 4.5.1
RazorGenerator.Mvc 2.3.4
Nuget Package Manager for Visual Studio 2.8.60318.734
Microsoft ASP.NET MVC 5.2..3

**Comment by Erok21** [comment]
To clarify, my menu lives in one project that is published to a nuget package, then added to my other solutions. this issue happens whenever I update the other solutions.

**Comment by pranavkm** [comment]
Isn't this a NuGet issue?

**Comment by davidebbo** [comment]
Yes, that's a NuGet annoyance, which I've also noticed before. So valid issue, but wrong place :)

**Comment by Erok21** [comment]
Thanks for the heads up! I've never seen it elsewhere, nor did I find
anything on it, so I figured it was here. Thanks for the feedback.
