### ISSUE TITLE
Azure - Attempted to access an element as a type incompatible with the array.

### ISSUE THREAD

**Issue by ladinek82** [RazorGenerator/RazorGenerator#205]
Hi, 

I use your RazorGenerator in my project and the project works good on virtual or physic servers. I have deployed the same code to Azure, where the web project is hosted like typical web site and I have this error. 

`Attempted to access an element as a type incompatible with the array.
   at System.Collections.Generic.List'1.Insert(Int32 index, T item)
   at System.Web.Mvc.ViewEngineCollection.InsertItem(Int32 index, IViewEngine item)
   at Neurodot.Logging.UI.RazorGeneratorMvcStart.Start()
`
My code is here

`
    public static class RazorGeneratorMvcStart {

		private static bool _startMethodExecuted = false;

		public static void Start() {

			if (_startMethodExecuted == true)
			{
				return;
			}
			var engine = new PrecompiledMvcEngine(typeof(Neurodot.Logging.UI.RazorGeneratorMvcStart).Assembly)
			{
				UsePhysicalViewsIfNewer = HttpContext.Current.Request.IsLocal
			};

			ViewEngines.Engines.Insert(0, engine);

            // StartPage lookups are done by WebPages. 
            VirtualPathFactoryManager.RegisterVirtualPathFactory(engine);

			_startMethodExecuted = true;

		}
	}
`
I don't know where is the problem. Can you help me? 
Thank you very well.

**Comment by ladinek82** [comment]
Sorry, my fault.

**Comment by Jehoel** [comment]
@ladinek82 For the benefit of other users, can you explain what the problem was and how you fixed it? As far as I can tell from here your code looks okay.

**Comment by ladinek82** [comment]
Yes, I can. The problem was in conrruption the files during deployment to Azure. I don't know why. I deployed the files to Azure and few files (dll libraries) had zero size. 
The solution was very easy. I had to deploy again and if the files correct the project worked.
