### ISSUE TITLE
The name 'WriteAttribute' does not exist in the current context problem with generating code

### ISSUE THREAD

**Issue by gasperhLex** [RazorGenerator/RazorGenerator#217]
Hi,

I've been having some problems with generating code via RazorGenerator, namely with passing any code based argument in html params like so: 

```
@*
    Generator: Template
    TypeVisibility: Public
    GeneratePrettyNames: true
    Namespace: Pages
*@

@inherits RazorPage

@{
    Layout = new LayoutPage("Services");

    *some list* listOfUrls = getList(); //whatever you use to get a list of ulrs
}
```

```
@for(item in listOfUrls)
{
  <div>
    <a href="@item.Url"> Link </a> // When generating code via Razor Generator returns the error bellow
    <p>@item.Url</p> // Compiles okey
  </div>
}
```

Error CS0103: The name 'WriteAttribute' does not exist in the current context - HangfireServer in ServicesPage.generated.cs

The same error also happens in onclick="SomeFun(@item.Param)"

Also. It works if I pass in raw html as `@Html.Raw(string.Format("<a href="{0}"> Link </a>"), item.Url)`

Cheers

**Comment by Jehoel** [comment]
The `WriteAttribute` call is added behind-the-scenes because you're writing out a HTML attributes.

The `WriteAttribute` method is defined in the base-class of the page you're using. In your `.cshtml` file you've posted you're supplying your own `RazorPage` base class which won't have `WriteAttribute` defined.

If you remove the `@inherits RazorPage` line it should work.

**Comment by gasperhLex** [comment]
@Jehoel Hi, thank you for the fast response. Unfortunally removing the inherits created more problems then there were. 

If I change the generator file and do some changes to the code (removing some stuff that I dont want to remove), yeah it compiles and generates the .cs file, but for the template generator it doesnt. 

I should probalby look into the base class im providing.

**Comment by Jehoel** [comment]
> @gasperhLex  Unfortunally removing the `inherits` created more problems then there were.

What kinds of problems does it introduce?

**Comment by gasperhLex** [comment]
I see the problem. The RazorPage isnt from ASP.NET as it seems.  I've been using the Hangfire RazorPage that only has WriteLiteral and Write. That explains it. Yeah.. that makes sense.

Well that does it hah :) thank you for the help
