### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by Daddoon** [RazorGenerator/RazorGenerator#225]
Hi !

Is there any Visual Studio 2022 support planned ?

Thanks !

**Comment by Jehoel** [comment]
I'm not a Microsoft _blue-badger_ anymore, so I don't have good access to VS 2022 builds - but ostensibly, yes.

**Comment by Daddoon** [comment]
Hi @Jehoel , thanks for your reply.

The VS2022 Preview [is available here](https://visualstudio.microsoft.com/fr/vs/preview/vs2022/)

What content do you expect from the VirtualBox image to be set ?

Also, my concern and so the reason of this question, is that due to the changing nature of VS2022 extensions implementations (Out of Proc ?) and the 64 bit behavior, i don't know if it's hard to migrate from the old extension behavior, to theses new one.

**Comment by Jehoel** [comment]
Actually it's a _good thing_ because running out-of-proc means that RazorGenerator could run Razor for ASP.NET Core in .NET Core, instead of being stuck in .NET Framework 4.8.

**Comment by Daddoon** [comment]
But do you think that it will still work for ASP.NET MVC 4 / 5 projects ?
I'm asking because i'm still working on a Legacy project for a client.

Yes out of proc should be good, but i have no idea what it implie in terms of work on this project.
What do you need from the VM Image ?

Cool that you have already tested some things (with or without Hatsune Miku names !), you surely have a wider view than me on the requirements and possibilities of this.

**Comment by Jehoel** [comment]
> But do you think that it will still work for ASP.NET MVC 4 / 5 projects ?

Yes, it should still work. Even though the hosting model has changed, it looks like the all-important `EnvDTE` is still accessible so that's all that matters.

The bulk of `RazorGenerator` runs entirely independently of Visual Studio. The VSIX is only there to enable the `Custom Tool` integration - (and personally I'd prefer it if everyone ditched it and switched to the MSBuild version instead).

> I'm asking because i'm still working on a Legacy project for a client.

I hope you're getting paid enough to deal with legacy code.

> Yes out of proc should be good, but i have no idea what it implie in terms of work on this project.

From what I gather, it's not that big a change.

> What do you need from the VM Image ?

A VS 2022 install that _just works_.

> Cool that you have already tested some things

Calling it "testing" is stretching it - what actually happened is that I got drunk one night and thought it would be _fun_

> you surely have a wider view than me on the requirements and possibilities of this.

ahhahahahahahahah _\*dies\*_

**Comment by Daddoon** [comment]
> Yes, it should still work. Even though the hosting model has changed, it looks like the all-important `EnvDTE` is still accessible so that's all that matters.
> 
> The bulk of `RazorGenerator` runs entirely independently of Visual Studio. The VSIX is only there to enable the `Custom Tool` integration - (and personally I'd prefer it if everyone ditched it and switched to the MSBuild version instead).
> 

Wait a minute ! I can already do this with a MSBuild version existing somewhere ?? 😆 

> 
> I hope you're getting paid enough to deal with legacy code.
> 

I have no clue, but i imagine that this is enough !

> 
> From what I gather, it's not that big a change.
> 

Ok !

> 
> A VS 2022 install that _just works_.
> 
> Calling it "testing" is stretching it - what actually happened is that I got drunk one night and thought it would be _fun_
> 

"Beer: Think Different"
Sometime some little alterations can be good in order to have a kind of...new point of view on things ! 😆 

> ahhahahahahahahah _*dies*_

R.I.P

**Comment by Daddoon** [comment]
Hi @Jehoel !

I just made a PR here if your are interested: https://github.com/RazorGenerator/RazorGenerator/pull/227

**Comment by CZEMacLeod** [comment]
For reference I've been using the MSBuild version with VS2022 quite successfully since the preview 1 release.
Also note that VS2022 installs side by side with previous versions, and so does not interfere with development, so the use of a VM is not such a requirement.
If you need help with package splitting for multitargetting VS2019 and VS2022, there are some great videos by @madskristensen on [YouTube](https://youtu.be/-PKIPTW6km0) and the excellent [Community.VisualStudio.Toolkit](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit) which makes it easier to abstract to the different versions.
I hope this helps for maintaining the VSIX version - although the [MSBuild](https://www.nuget.org/packages/RazorGenerator.MsBuild/) version makes all that redundant, and also works on build servers with nothing else installed.

**Comment by Daddoon** [comment]
@CZEMacLeod Thanks for your feedback.

Unfortunately, on my side, the RazorGenerator.MSBuild package does not work at all on the very old legacy project i'm working on for a client. It just fail the build without any error logged into the VS2022 output window.

Using the legacy RazorGenerator.Tooling project (the VSIX extension) is the only thing that keep my old project working.

Thanks for the Youtube video link, this mean that targeting with the new Visual Studio SDK model (through NuGet instead of Framework Extension) should still working with older versions of Visual Studio.

It seem that @Jehoel started working on a multi-version build ? Seeing this branch: https://github.com/RazorGenerator/RazorGenerator/tree/multi-version

I'm having at least a temporary working solution on my side for working on VS2022 with my current constraints, but i'm not sure i will have the time yet on my side to multi-target this correctly.

**Comment by CZEMacLeod** [comment]
@Daddoon / @Jehoel : You might find some helpful folks over at Community.VisualStudio.Toolkit could help out, or perhaps even ask during one of the `Writing Visual Studio Extensions with Mads` live sessions.

@Daddoon - As for the MSBuild issues - remember to add the nuget package, remove the `Custom Tool` entry from all the razor pages and (optionally) change the `Build Action` from `Content` to `RazorSrcFiles`.
Also delete the code behind files generated by the add-in.
When you build, the code files will get generated in \obj\CodeGen and be included automatically for compilation.
Do not include these in your source control - they get generated and overwritten as required by the MSBuild task. Also, when you have it working, remember to delete the old code behind files from your source control too!

For legacy projects, sometimes you just have to keep lashing up the breaks and use the tools that work. So your temporary solution may just become your permanent fix. ;)

**Comment by Jehoel** [comment]
@CZEMacLeod @Daddoon Thanks - I'm looking at this now

**Comment by bnuzhouwei** [comment]
Nice work, I am upgrading my old project to VS2022, but can't find the RazorGenerator in VS Store.

Thanks very much.

**Comment by ze-pequeno** [comment]
@Jehoel @Daddoon @CZEMacLeod Visual Studio 2022 is now out. Is there a chance to get a compatible or specific version of the extension for Visual Studio 2022 ? The sample from the #227 PR seems to work but is not available officialy.

**Comment by Daddoon** [comment]
@ze-pequeno I'm unfortunately not a maintainer of this repo. I think @Jehoel  must do something about this. In the worst case, someone may upload this as an other product on VS Marketplace but this is not ideal, like "RazorGenerator 2022", like someone else did it for some Mads Kristensen tools.

The "only" issue with my PR is that it was not targeted to be specifically backward compatible with older version of Visual Studio. It may be done, as maybe the new VS Extension model is maybe backward compatible even if it's not using some COM interface directly from Visual Studio, but not guaranteed at all.

@Jehoel : Some advices ?

**Comment by Daddoon** [comment]
Just for info, as there is no answer from @Jehoel, like some other author on other plugins, i did publish a forked version of RazorGenerator, available here: https://marketplace.visualstudio.com/items?itemName=GuillaumeZahra.razorgenerator2022

**Comment by ze-pequeno** [comment]
@Daddoon Thanks I will install it soon :)

**Comment by bartcoppens** [comment]
Thanks! Installed. Seems to work fine.
The file generation doesn't seem to trigger on save though.
Looks like I need to manually "Run custom tool".
Am I missing something?

**Comment by Daddoon** [comment]
@bartcoppens I work by default on my projects. Is  "RazorGenerator" written in the CustomTool property ?
My VS2022 installation is in French, but my files should be something in English like:

Generate Action: Included
Copy in Folder: Do not copy
Namespace of the tool: Empty
Custom Tool: RazorGenerator

Is the Extension listed in your VS extension list as installed ?
Are you using VS2022 or VS2022 Preview ?

Worked out of the box for me.

**Comment by bartcoppens** [comment]
I confirm it works correctly after restarting Visual Studio

**Comment by davidebbo** [comment]
We should try to get this in the official one. So @Daddoon, from what I can see, your PR was never merged in? I see you now closed it, so we should probably reopen it and get it in.

I haven't used VS in a few years, but I should be able to install 2022 on some old machine and get it built and published.

**Comment by Daddoon** [comment]
I published the extension on my side on the meantime, as a fork, but feel free to take precedence over my PR and publish an update.

I would then remove my extension from the store.

The only possible missing thing on my PR, is that i didn't tested if it would work on older versions of Visual Studio (i mean if you remove the soft limit in the vsix manifest).

**Comment by davidebbo** [comment]
Thanks Guillaume. Any chance that someone can do a quick test to make sure it still works on earlier VS versions?

**Comment by davidebbo** [comment]
Ok, I pushed new version 1.13.0, which should support both older VS (starting with VS 2017) and the newest 2022.

Caveat: I was only able to test VS 2022, so if you run into problems with older ones, let us know.

**Comment by Daddoon** [comment]
Will do a test on VS2019 tomorrow or Monday if no one try before me.

**Comment by davidebbo** [comment]
Thanks Guillaume!

**Comment by Daddoon** [comment]
Did you update the manifest as intended ?
I do see Razor Generator 1.13.0 listed from VS2022 and VS2022 Preview, but it has totally disappeared from VS2019.

I think VS2019 cannot fetch it from the Marketplace for now.
Something in the VSIX is maybe wrong.

**Comment by Daddoon** [comment]
I think i should to a quick test from source tomorrow, and see in wich configuration the VSIX is manually installable with both VS2019 and VS2022 configuration, as it seems you don't have access to VS2019 for now.

**Comment by davidebbo** [comment]
Ah crap, I thought it would work based on the manifest changes I made: https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Tooling/source.extension.vsixmanifest. I tried to follow https://stackoverflow.com/questions/67769432/error-vssdk1311-about-productarchitecture-when-building-extension-for-vs2022.

**Comment by davidebbo** [comment]
Also, some info on [this page](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) but it's not super clear.

**Comment by Daddoon** [comment]
I think there is a typo error on your side.

I think theses kind of line:

```xml
<InstallationTarget Version="[15.0,16.0]" Id="Microsoft.VisualStudio.Community">
   <ProductArchitecture>x86</ProductArchitecture>
</InstallationTarget>
```

Should be this instead:

```xml
<InstallationTarget Version="[15.0,16.0)" Id="Microsoft.VisualStudio.Community">
  <ProductArchitecture>x86</ProductArchitecture>
</InstallationTarget>
```

I'm maybe wrong, but if you put a ] instead of a ) , maybe 16.x version after strictly 17.0 versions are excluded ?

**Comment by Daddoon** [comment]
I will take a look on this in order to publish the correct update if you want, but i will not be available for that before Monday.

**Comment by davidebbo** [comment]
Good catch! I republished it with that change (still as 1.13.0)

**Comment by Daddoon** [comment]
Not visible at the moment. I will try a little later.

**Comment by davidebbo** [comment]
I published it as a release in case you want to try the VSIX directly (not through marketplace): https://github.com/RazorGenerator/RazorGenerator/releases/tag/v1.13.0

**Comment by Daddoon** [comment]
Thanks !

**Comment by Daddoon** [comment]
I tried to target all Visual Studio at the same time with something like this:

```xml
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Community">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Community">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Pro">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Pro">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Enterprise">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[15.0,)" Id="Microsoft.VisualStudio.Enterprise">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
```

However it doesn't work on VS2019, and so i imagine, same for earlier version.

In my opinion, this surely mean that you can't use the new **NuGet model** for Visual Studio extensions development on previous versions of Visual Studio, i think it's supported only for VS2022 and afterward.

The recommendation of Microsoft in order to maintain 2 versions of an extension at code level, is to use a **Shared Project** for the core of the extension, and also use some defined constants in order to adapt the code for the COM version and for the new NuGet extension format.

Then you would reference this project, set the constant, and the right COM's on the VS2019 and earlier on one side, and on the other project, reference the shared project and only include the required NuGet. With the conditional compilation would be right.

But in short term you can't have a VSIX that target the old AND the new model simultaeously...It will be two VSIX.
Visual Studio Marketplace does not allow multiple VSIX for one product, even if it was on the roadmap. As you can see on the doc page:

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

> In the future, the Marketplace will allow you to upload multiple VSIXs to just one Marketplace listing. You can then upload your Visual Studio 2022-targeted VSIX and a VSIX for an earlier version of Visual Studio. Your users will automatically get the right VSIX for the Visual Studio version they've installed, when they're using the Visual Studio extension manager.

The right steps for this project is:

- [ ] Migrate the tooling project content in a Shared Project.
- [ ] Create a **RazorGenerator.Tooling.Amd64** (or something else but i think it will be nice as VS2022 is the first release to be 64 bit only, and so using the new model)
- [ ] Reference COM needed in **RazorGenerator.Tooling** as before
- [ ] Reference NuGet packages needed for **RazorGenerator.Tooling.Amd64** as for now
- [ ] Create the right VSIX manifest for each Tooling project
- [ ] Create the conditional statements for each project in the Shared Project.
- [ ] As Visual Studio Market place does not support multiple VSIX for the same extension, create a new extension ID for the VS2022 revision. If we can't use the same name for this release, at least calling it Razor Generator 2022+ ?

Feel free to comment if you have any remarks.

**Comment by davidebbo** [comment]
Thanks for investigating. Maybe the cheaper alternative is to go back to the fork approach:

- Create a VS 2019 branch with the old code
- Use master for 2022, and only have it target 2022+
- Use a different extension GUID

So... basically exactly what you had done. :) Except we make it official. The only downsides I can think of are:

- the old installation count will not carry
- we lose the reviews
- Anything else?

I'll leave it to you to decide what approach to take. If we do this, it also makes it cleaner to create a new VSIX Publisher identity to add you to (although that bug makes it difficult).

I only have access to a Mac for the next two weeks, but if you upload a VSIX to GitHub as a (pre)release, I can publish it. We'll find a way to get you Publishing access, maybe by contacting support.

**Comment by Daddoon** [comment]
As we don't know when Visual Studio MarketPlace will support multi-vsix shipping, i think it's safer to have two different versions.
I suggest to call the VS2022 version **Razor Generator (64 bits)** or **Razor Generator 2022+** . What do you prefer ? I doubt we can keep the same Extension name exactly.

Also:
- I have created a new branch on the repo called **x86_branch** . It was the last commit of Jehoel some years ago for VS2019 (and i also forgotten that i was also the one who provided the PR at that time, funny...).
- I have created a new entry under **Release** on GitHub, as it seem the public VSIX release of the 1.12 version was forgotten, and it was the one who give the VS2019 support. Thanksfully i was having a copy of the extension VSIX somewhere.
- You may remove the 1.13 version from the store and only keep the 1.12 version that was working ?

**Comment by Daddoon** [comment]
In doubt of support or lack of support for extensions with same display name but different Identity....Here are two VSIX of Razor Generator for VS2022.

- Both have a new Identity for the store in order to be different from the RazorGenerator - VS2019 and earlier version.
- This new identity is of course the same on the two files.
- The only difference is that one is compiled with display name "Razor Generator" as the main/previous iteration of Razor Generator , and the second one "RazorGenerator (64-bit)".

This way, you may try to upload the "Razor Generator" version first. If you have an issue on the Marketplace because of a possible duplicate name, upload the alternate version.

Find the ZIP file attached.

[razor alternate.zip](https://github.com/RazorGenerator/RazorGenerator/files/7741354/razor.alternate.zip)

**Comment by davidebbo** [comment]
Marketplace is continuing to make our life difficult. :( It only keeps the last version, so I can't just delete 1.13 and have it go back to 1.12. And to make things worse, it will not let me reupload the older one:

    Version cannot be decremented. Needs to be equal to or higher than 1.13.0.

Sorry, it's my bad, I should not have pushed the 1.13 version until we had time to better test it. Anyway, at this point it seems the only thing we can do is rebuild the x86_branch branch as 1.13.0 (or higher, whatever).

Side note: the VSIX you uploaded to the 1.12.0 release appears to actually be 1.11.1, though at this point, ir probably doesn't matter.

I have not yet looked at the 64 bit version, so I'll tackle that next.

**Comment by davidebbo** [comment]
Ok, a little bit of good news: I was able to publish the 2022 version using the same name. You can see it on https://marketplace.visualstudio.com/items?itemName=RazorGeneratorContributors.RazorGenerator.

Note that I created it under a different **publisher** called `RazorGeneratorContributors`, which is cleaner than it being under a DavidEbbo contributor (the old extension is https://marketplace.visualstudio.com/items?itemName=DavidEbbo.RazorGenerator). Of course, I still can't add you there because of the [invalid domain bug](https://stackoverflow.com/questions/56032912/vs-marketplace-add-member-displayes-invalid-domain-error). We'll get that addressed.

Please verify that it works with 2022. As it stands, I think you will see both the old and new from VS 2022 (until we fix up the old). You should be able to tell them apart from the Publisher name.

**Comment by Daddoon** [comment]
> Marketplace is continuing to make our life difficult. :( It only keeps the last version, so I can't just delete 1.13 and have it go back to 1.12. And to make things worse, it will not let me reupload the older one:
> 
> ```
> Version cannot be decremented. Needs to be equal to or higher than 1.13.0.
> ```
> 
> Sorry, it's my bad, I should not have pushed the 1.13 version until we had time to better test it. Anyway, at this point it seems the only thing we can do is rebuild the x86_branch branch as 1.13.0 (or higher, whatever).
> 
> Side note: the VSIX you uploaded to the 1.12.0 release appears to actually be 1.11.1, though at this point, ir probably doesn't matter.
> 
> I have not yet looked at the 64 bit version, so I'll tackle that next.

Strange, as i see on the tags of Jehoel the 1.12 number shown, and no official release about the VS2019 support , i mean on GitHub. But i can confirm that the provided VSIX for 1.12 does install on VS2019, as i tested before sending it.

Bad news for the 1.13 thing for the publication...as from the default x86_branch, i'm not able to build in the current state, as there is some incorrect things, in my opinion, between the referenced COM references, the "Prerequisite" targetting some 15.0 VS components, but the extension is also targetted for 10.0 in it's manifest.

I have to do some fixes on this branch in order to make it buildable with current tooling and according to the manifest "prerequisite" mentionned, i should target VS 15.0 as a minimum, so VS2017 as the minimum target.

Is this problematic ?

**Comment by Daddoon** [comment]
The Razor Generator publication you made for VS2022 (with 0 votes) works as intended !

I have at least 3 Razor Generators shown (The current that don't work on older VS , my own iteration that i can safely remove, and the one you just published).

![image](https://user-images.githubusercontent.com/23449646/146689666-eb765fe6-41e9-493c-a4fa-65349ddaeae1.png)

I will remove my publication on the marketplace

**Comment by davidebbo** [comment]
Great for the VS2022 version!

For the older vsix, it's strange. If you download the one from the 1.12 release (https://github.com/RazorGenerator/RazorGenerator/releases/download/v1.12.0/RazorGenerator.vsix) and look inside it (vsix is just a zip file, rename it to .zip), the manifest definitely says 1.11.1.

BTW, if you really think that's the right VSIX for 2019, I wonder if we can just do some surgery on it. i.e. just change the version in the manifest to 1.13.0, and zip it back up. As long as there is no signature, maybe that'll work?

If that's not an option, I have no problem with requiring at least 2017.

**Comment by Daddoon** [comment]
You are right about the versioning. In reality the VSIX i sent you is the original build i made in my VS2019 PR, and i called it 1.11.1 myself at the time.

Then it was 1.12 on the Marketplace because Jehoel as changed the version, as seen on the last commit: https://github.com/RazorGenerator/RazorGenerator/commit/937972e94d83e71a5a1d372e81c2de98723c1165

But in reality it's the same build.
You are right, if we are able to just modify the manifest, it would be better then restoring all the Visual Studio tooling. Still i'm wondering why i didn't had theses error two years ago, maybe because i was using VS2017 and expecting to compile it for VS2019.

I will test and tell you if it work. If yes, we can try to upload a ...1.13.1 version that exclude VS2022. I wish there is not another bug that would prevent it to be removed from the support !

**Comment by davidebbo** [comment]
Ok, so I tried the 'surgery' and it appears to have worked. I just made it 1.13.0 again (using your 1.11.1 as a base), and published it. 

Can you check if VS 2019 can see it now (and that it works)?

**Comment by Daddoon** [comment]
Ho i just finished the same thing on my side (same surgery). Ok i will check just now.

**Comment by Daddoon** [comment]
No it didn't work. But i know why, you forgot some others references of 1.11.1 in some other files (I just replaced them all with Notepad++).

Either you replace theses missing reference by yourself, or you can use this VSIX (The VSIX is in the ZIP file, as i can't upload VSIX directly on a GitHub post, so you must extract him first).

[RazorGenerator.1.13.1.VS2019.zip](https://github.com/RazorGenerator/RazorGenerator/files/7741602/RazorGenerator.1.13.1.VS2019.zip)

However i named it 1.13.1...Do i need to change it ?

**Comment by Daddoon** [comment]
Wait, i still have the thing opened, i may just upload a 1.13 naming one

**Comment by davidebbo** [comment]
Ok, I'll let you do it! I'm on a Mac and I'm not well equipped to do it. I guess 1.13.1 is fine, but the Marketplace is perfectly happy with reusing the same version. Either way is fine!

**Comment by Daddoon** [comment]
Here is the same file but as 1.13. Just installed and tested it on VS2019, working fine.

[RazorGenerator.1.13.VS2019.zip](https://github.com/RazorGenerator/RazorGenerator/files/7741613/RazorGenerator.1.13.VS2019.zip)

**Comment by Daddoon** [comment]
Also good news, the 1.13 versions from the original ID of the manifest has disappeared from VS2022 Extensions list in Visual Studio, so only the Razor Generators you just built today that target VS2022 (and later) is visible. Perfect.

Keep me informed when the update 1.13 for VS2019 and earlier is live. I will then try to install it from the feed just to be sure !

**Comment by davidebbo** [comment]
For some odd reason, it was not happy with your 1.13.0:

    Upload failed: TF400898: An Internal Error Occurred. Activity Id: ad0108a2-68dc-420f-8ccb-b96f12f2ea56.

I tried 3 times and got this error, so it's not random. Hard to know what's wrong.

I tried your 1.13.1, thinking I would get the same error, and somehow it seems to have gotten through!

Fingers crossed that it actually works...

**Comment by Daddoon** [comment]
Strange, it's just the same as 1.13.1 ! Surely a Visual Studio Marketplace mistery as i just tested it before sending it to you.
I will try your release on VS2019.

**Comment by Daddoon** [comment]
It works !

I think we can close this issue now.

Do we have to update the Release page VSIX and Tag name ? And adding two VSIX on a 1.13 Release, targeted for VS2019 and earlier, and the other for VS2022 ?

**Comment by davidebbo** [comment]
Awesome! Man, that was way more painful than I expected. Thanks for helping drive this!

I think it's fine to just upload both to the same release, and just update the description to explain the situation. Hopefully that's the last ever release for older VS. And hopefully it'll just work with pain with the next version of VS since we left it open ended.

**Comment by Daddoon** [comment]
Agreed !

Are you doing this edit/new 1.13 release note or must i do it ?

**Comment by davidebbo** [comment]
I just updated https://github.com/RazorGenerator/RazorGenerator/releases/tag/v1.13.0. I noticed the vsix for VS 2022 is 3 times the size. Hopefully that's expected!

**Comment by Daddoon** [comment]
Strange, it's 1.9MB if you download it directly for Visual Studio Marketplace Web page https://marketplace.visualstudio.com/items?itemName=RazorGeneratorContributors.RazorGenerator

I don't know if it's a different file or simply a weird "rounding" from GitHub.

**Comment by davidebbo** [comment]
If you download from GitHub, it's actually 4.6MB. But if you unzip it and rezip it, it's 1.9. So for some reason, the one you put on GitHub was zipped with a very low compression level. I doubt the GitHub changed it, it keeps the exact binaries you upload.

Anyway, maybe not worth worrying about at this point!
