### ISSUE TITLE
Razor Generator on Visual Studio 2010

### ISSUE THREAD

**Issue by nobruds** [RazorGenerator/RazorGenerator#23]
Hello,

I was using the RazorGenerator.Mvc dll on my VS2010 Project. 
But now when I try to run the custom tool to regenerate my code I get the error: "Cannot find custom tool RazorGenerator"

this wasn't supported by VS2010? I can't find it on extension manager to install anymore.

Thanks

**Comment by davidebbo** [comment]
Indeed, it no longer supports VS2010 to reduce the test matrix and maintenance cost. The supported versions are 2012, 2013 and 2015.

Can you upgrade your VS? 2010 is really ancient :)

**Comment by nobruds** [comment]
Hi, thanks for the reply.

Yeah, We are trying to get the company to buy VS 2015 (or 2013). Maybe next semester.
until them I will try something else.

I can't use with the VS Express version right ?

thanks

**Comment by pranavkm** [comment]
@nobruds unfortunately not. The express editions does not allow installing third party extensions (like RazorGenerator). You could consider using VS 2015's community edition - https://www.visualstudio.com/en-us/products/vs-2015-product-editions.aspx - if that works for you.

**Comment by amitdhanbad** [comment]
Hello,

I was using the RazorGenerator.Mvc dll on my VS20103 web Project. 
But now when I try to run the custom tool to regenerate my code I get the error: "Cannot find custom tool RazorGenerator"

this wasn't supported by VS20103 ? I can't find it on extension manager to install anymore.

Thanks

**Comment by davidebbo** [comment]
@amitdhanbad VS20103? I assume you mean VS2010 since that's what this issue relates to. If so, please see above.
