### ISSUE TITLE
signing the view for security

### ISSUE THREAD

**Issue by fasteddys** [RazorGenerator/RazorGenerator#231]
Can we [incorporate view signing](https://github.com/0xacb/viewgen)

![image](https://user-images.githubusercontent.com/96149622/162807704-e52ca20d-c84d-425e-9f38-747e8b31fc97.png)

**Comment by CZEMacLeod** [comment]
@fasteddys Not sure what you mean by this. RazorGenerator uses the MVC model and does not include any form of ViewState. 

- https://stackoverflow.com/a/23623614/1243548
- https://stackoverflow.com/a/1285568/1243548
- https://stackoverflow.com/a/366174/1243548
