### ISSUE TITLE
Error when building project.

### ISSUE THREAD

**Issue by jrabarton** [RazorGenerator/RazorGenerator#247]
I have just started using RazorGenerator.MSBuild to improve the response of a project I'm working on.

It seems to be exactly what I need, but I'm getting some strange messages that neither google or chatGPT can solve.

When I build my project I get the follow message in each of my cshtml files

```  error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'```

Any suggestions?

**Comment by CZEMacLeod** [comment]
@jrabarton I suggest first ensuring you have a reference to `Microsoft.CSharp`.

For my projects I also pull in the latest compilers with:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="3.6.0" />
  <PackageReference Remove="Microsoft.Net.Compilers.Toolset" Version="4.7.0" />
</ItemGroup>
```

There are some other tricks which I include in my [`MSBuild.SDK.SystemWeb.RazorLibrary`](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/blob/main/src/MSBuild.SDK.SystemWeb.RazorLibrary) SDK version, which wraps `RazorGenerator.MSBuild` into a full SDK type, allowing you to use the new SDK style projects for ASP.NET V4.x projects and does some of the configuration of packages for you. It also does things like update binding redirects automatically in both your main and views config files.

Can you confirm if the error is in the .cshtml file, or the .cs file generated from it? Are the .cs files being generated at all?

Other things that might be causing issues, are if your web.config file in your Views directory(s) are missing binding redirects, or other information required to do the transpile into csharp; or if you are relying on an assembly reference or namespace from that file that is not in your main web.config/app.config for the project.

If you can create a minimal working repo with the issue, it might help others to investigate and resolve this.

**Comment by jrabarton** [comment]
@CZEMacLeod you got it in one ... added the reference to ```Microsoft.CSharp``` and now it builds.

Thank you!

**Comment by CZEMacLeod** [comment]
@jrabarton Glad to be of help!
