### ISSUE TITLE
Build error caused by npm's node_modules

### ISSUE THREAD

**Issue by cjberg** [RazorGenerator/RazorGenerator#3]
One of my team members encountered an unexpected error during compilation recently:
```
RazorGenerator.targets(31,9): error MSB4018: The "RazorCodeGen" task failed unexpectedly.
RazorGenerator.targets(31,9): error MSB4018: System.ArgumentException: Illegal characters in path.
```
It turned out to be a bogus error message triggered by the addition of a node.js-module. The package manager _npm_ stores all project local packages in a subdirectory called _node_modules_, and this directory structure can get pretty deep as each module can have its own _node_modules_-directory. Once the path is longer than 260 characters (Windows API’s MAX_PATH), MSBuild breaks down and prints this bogus error.

The reason this occurs with Razor Generator is because of the following wildcard inclusion:

```
<ItemGroup>
  <RazorSrcFiles Condition=" '@(RazorSrcFiles)' == '' " Include="**\*.cshtml" />
  …
</ItemGroup>
```
It doesn’t seem to help excluding node_modules either; at least I wasn’t successful. Perhaps MSBuild traverses the directory structure before it excludes an item.

One possible solution is to move the item group inside the target PrecompileRazorFiles, and then build it by filtering the Content item group (created by Visual Studio):

```
<Target Name="PrecompileRazorFiles"
  Inputs="@(RazorSrcFiles)"
  Outputs="@(RazorOutputFiles)">
  <ItemGroup>
    <RazorSrcFiles Include="@(Content)" Condition=" '@(RazorSrcFiles)' == '' And %(Extension) == '.cshtml' " />
    <RazorOutputFiles Include="@(RazorSrcFiles -> '$(RazorViewsCodeGenDirectory)%(RelativeDir)%(Filename)%(Extension).cs')" />
  </ItemGroup>
  <RazorCodeGen ProjectRoot="$(MsBuildProjectDirectory)"
  …
</Target>
```

What do you think? Would it be possible to include this change in an official release, or do you know of a better solution?

I know I can fix this myself by scanning a known subset of directories before including this target, or by using a variant of the above method: my own target with a "BeforeTargets" construct combined with a dummy RazorSrcFiles-item to prevent the default scan from occurring (for want of a better conditional property). But I figure others will run into the same problem eventually, so maybe you want to fix it as well.

**Comment by davidebbo** [comment]
How are you getting the path to be longer than 260 characters in the first place? Typically, npm itself fails when it reaches that limit.

**Comment by cjberg** [comment]
I’m not sure, but it works. Perhaps it’s because npm is using relative paths and MSBuild doesn’t? If so, we’ve just been lucky so far.

I just found an npm issue “[Too many dependencies break the Windows file system](https://github.com/npm/npm/issues/3697)” where [Rebecca Turner says](https://github.com/npm/npm/issues/3697#issuecomment-71399211) it will be resolved in version 3: “npm@3's dependency resolution algorithm makes the node_modules folder as flat as possible”. That’s the best solution and v3 is probably not far away in time.

But that aside, wouldn't it be better to filter the Content item group than to include all cshtml files? If you exclude a cshtml file from a project temporarily, you wouldn’t expect it to be compiled, as it does now. Or do you need to support usage scenarios outside Visual Studio?

**Comment by pranavkm** [comment]
@cjberg, moving the `ItemGroup` might break the incremental compilation behavior (see the `Inputs` and `Outputs` attributes). 

Unfortunately MsBuild doesn't defining `RazorSrcFiles` outside the target. 
>> error MSB4190: The reference
to the built-in metadata "Extension" at position 2 is not allowed in this condition " '%(Extension)' == 'cshtml' "

I think this was primarily the reason we chose the current behavior.

**Comment by firelizzard18** [comment]
I fixed this by changing `RazorSrcFiles` to
    
    <RazorSrcFiles Condition=" '@(RazorSrcFiles)' == '' " Include="Views\**\*.cshtml; Areas\*\Views\**\*.cshtml" />

**Comment by pranavkm** [comment]
I like @firelizzard18's approach - perhaps we could throw in `App_Code\**\*.cshtml` in case people have helpers in that directory, but it should cover the most common places for views. @cjberg, thoughts?

**Comment by cjberg** [comment]
I'm sorry for the late reply. Well, @firelizzard18's approach is exactly what we did at first. It works as long as you have the standard template view folders (Views and Views under Areas). In our project, however, we have several different, non-standard view folders, so it wouldn't have worked for us out of the box. It's easy to customize once you understand how it works, of course, but not everyone enjoys or understands MSBuild customization, so it could prove difficult for some.

As for _incremental compilation support_ one can always use an additional helper-task that `PrecompileRazorFiles` depends on:

```
<Target Name="_ResolveRazorFiles">
  <ItemGroup>
    <RazorSrcFiles Condition=" '@(RazorSrcFiles)' == '' and '%(Extension)' == '.cshtml' "
      Include="@(Content)" />
    <RazorSrcFiles Condition=" '@(RazorSrcFiles)' == '' "
      Include="**\*.cshtml" />
    <RazorOutputFiles
      Include="@(RazorSrcFiles -> '$(RazorViewsCodeGenDirectory)%(RelativeDir)%(Filename)%(Extension).cs')" />
  </ItemGroup>
</Target>

<Target Name="PrecompileRazorFiles"
  Inputs="@(RazorSrcFiles)"
  Outputs="@(RazorOutputFiles)"
  DependsOnTargets="_ResolveRazorFiles">
  <!-- Same as before -->
</Target>
```
`_ResolveRazorFiles` will create `RazorSrcFiles` by filtering the `Content` item group, and fall back on scanning the project directory if `Content` is empty somehow (a non-standard build process). Since `PrecompileRazorFiles` makes use of `DependsOnTargets`, `_ResolveRazorFiles` will always run before it and `Inputs`/`Outputs` will then be able to determine if the task needs to execute.

I think this approach would be fully backward compatible and a little bit better integrated with Visual Studio's build process. If one excludes a file from the project, it will not be precompiled.

**Comment by pranavkm** [comment]
This looks pretty great - would you like to send a PR for this?

**Comment by cjberg** [comment]
Thanks for accepting the pull request! I'm closing this issue now.

**Comment by kb3eua** [comment]
When can we expected an update RazorGenerator.MsBuild package on NuGet containing this fix?

**Comment by davidebbo** [comment]
I just pushed 2.3.4. Can you give it a try?

**Comment by kb3eua** [comment]
I seem to be error free now with 2.3.4... Thanks!
