### ISSUE TITLE
Installing RazorGenerator.MsBuild nuget package instantly enables RazorGenerator.MsBuild.targets

### ISSUE THREAD

**Issue by radiok** [RazorGenerator/RazorGenerator#32]
I have been manually modifying my project files as follows...
`<Import Project="packages\RazorGenerator.MsBuild.2.3.6\build\RazorGenerator.MsBuild.targets" Condition="'$(PrecompileRazorFiles)'=='true' AND Exists('packages\RazorGenerator.MsBuild.2.3.6\build\RazorGenerator.MsBuild.targets')" />`
From...
`<Import Project="packages\RazorGenerator.MsBuild.2.3.6\build\RazorGenerator.MsBuild.targets" Condition="Exists('packages\RazorGenerator.MsBuild.2.3.6\build\RazorGenerator.MsBuild.targets')" />`
Without that additional condition, the RazorGenerator.MsBuild.targets file is executed regardless of my PrecompileRazorFiles setting.

**Comment by radiok** [comment]
The more I look into this, this might be my own problem, I don't see any references that the RazorGenerator developers intend for the MsBuild targets to conditionally execute.  Either you install the nuget package and they execute, or you remove it and they don't.  Is that correct?

**Comment by pranavkm** [comment]
@radiok yeah it's not designed to be conditionally used. We'd be open to accept a PR to `RazorGenerator.targets` that allows this:

```xml
        <CompileDependsOn Condition=" '$(PrecompileRazorFiles)' == 'true' >
            PrecompileRazorFiles;
            $(CompileDependsOn);
        </CompileDependsOn>
```

where `PrecompileRazorFiles` is true by default
