### ISSUE TITLE
Add generic type parameters directive

### ISSUE THREAD

**Issue by atifaziz** [RazorGenerator/RazorGenerator#34]
Allow generic type parameters on generated class via a new directive like the following:

    @* GenericParameters: TModel *@

This would add the generic type parameter `TModel` as illustrated below:

```c#
partial class SomeClass<TModel> { /* … */ }
```

It should be possible to specify multiple type parameters as a comma-separated list:

    @* GenericParameters: T1, T2, T3 *@

**Comment by davidebbo** [comment]
This sounds more like a Razor feature request than something that should be RG specific. Generally, the goal of RG is not to add new features that don't exist in Razor, but is to allow the precompilation of Razor pages. Not saying that we could never add new features, but more sharing the high level guideline that we're following.

**Comment by atifaziz** [comment]
@davidebbo I see. I didn't know exactly where to draw the line, where Razor ends and RG starts.  I was under the impressions that RG had some modest amount of control on the output class definition.

**Comment by davidebbo** [comment]
It does have some control. Basically, it gets a CodeDOM tree from Razor, and can change stuff. I suppose if you think this is an important extension to Razor, we can look into getting it in RG. Do you want to try making that change and sending a PR?

**Comment by atifaziz** [comment]
@davidebbo I can certainly give it a shot if it helps to get it in there faster. However, it's always a question of being familiar with the code base (which I am not) that can make the difference between a pleasant 15 minute session and an hour or two of frustration to make the enhancement, test and create the PR. And so it boils down to if it's quicker for you or me to the make the change. :smirk:

That all said, I'm willing to give it a shot if you can point me in the direction of which file & solution would be my starting point and how I can go about testing and then I can work my way from there. And if  I completely and utterly missed some “Contribution Guide” written on the wall then feel free to hit me with a :hammer: and send me a gentler pointer/link. :smile:
