### ISSUE TITLE
Visual Studio 2013 Errors since Update 5 install

### ISSUE THREAD

**Issue by princeo911** [RazorGenerator/RazorGenerator#39]
I noticed that when I start a new instance of visual studio and load up a project with razorGenerator in it I get a warning in package manager studio, that seems to work work I think when I select Run Once, How do I stop the messages from coming up?

![razorgenerator startup](https://cloud.githubusercontent.com/assets/13858033/9428945/2c17bed4-49b7-11e5-9f86-790914398410.png)
![razorgenerator startup2](https://cloud.githubusercontent.com/assets/13858033/9428946/2ec37bb4-49b7-11e5-915d-c40297853c2e.png)

**Comment by princeo911** [comment]
This may also be related but it seems to me that the same issue causes another issue I have raised
https://github.com/NuGet/Home/issues/1240

Updating nuget packages somehow buggers up because of the same error message above.

**Comment by davidebbo** [comment]
This sounds like a general NuGet warning for packages that has scrips, and not something related to RazorGenerator. Best to close this one and track on NuGet.

**Comment by princeo911** [comment]
I think you are right. Hopefully find a solution. will comment here if I find a solution (which is looking like a reinstall).
