### ISSUE TITLE
No vsix version 1.6.4 available anymore

### ISSUE THREAD

**Issue by stesieber** [RazorGenerator/RazorGenerator#4]
Our whole team is working with RazorGenerator v 1.6.4, we have a rather large solution with many different projects containing cshtml files.
Version 1.7.0 introduced breaking changes (Generate Pretty names : false by default). As  members are joining, they need to install the same version of razor generator as the rest of the team. We're in the middle finishing a release so updating Razor Generator is currently no option.

Is it possible for you to keep an archive of old versions of razor generator? This will also reduce the risk for coming releases. Note that we had similar issues between 1.6.0 and 1.6.4.

**Comment by davidebbo** [comment]
Please check out https://github.com/RazorGenerator/RazorGenerator#trimming-leading-underscores-in-generated-class-names, which shows how you can turn off this behavior for your whole app using a `razorgenerator.directives` file.

**Comment by davidebbo** [comment]
As an aside, I do wish the VS extension gallery allowed selecting older versions, the way NuGet does. But it does not support that. Still, I'm hoping you'll find that you don't' need to go back.

**Comment by stesieber** [comment]
Thanks for the answer David! I'm aware of the mentioned issue. I assumed that it is not possible to provide multiple version in the VS extension gallery.
For me it would already be great to have the vsix file somewhere for manual download. For future releases, this would help to offer all users a plan B if something is broken after the update.

**Comment by davidebbo** [comment]
Agreed, it would be worth starting to do that. Did the `razorgenerator.directives` file fix your issue?

**Comment by stesieber** [comment]
Yeah, we were able to fix the issue with putting the razorgenerator.directives file in every of our web projects. Thanks for asking.
