### ISSUE TITLE
Custom Build Action

### ISSUE THREAD

**Issue by TheJayMann** [RazorGenerator/RazorGenerator#48]
Can the targets file included with the RazorGenerator.MsBuild package be modified to allow RazorSrcFiles to be selected in the BuildAction?  This would allow selectively generating classes from razor views, rather than generating all.  It should be as simpe as adding the following item group in the .targets file:

```
    <ItemGroup>
         <AvailableItemName Include="RazorSrcFiles" />   
     </ItemGroup>
```

**Comment by pranavkm** [comment]
You should be able to specify an item group named `RazorSrcFiles` in your csproj. This should override the value we calculate in the target without having to modify it.

**Comment by TheJayMann** [comment]
I realize I can create an item group with RazorSrcFiles to get this functionality, and it is what I'm doing.  What I'm looking for is a way to make it easy to select RazorSrcFiles as a Build Action in Visual Studio.  By default, RazorSrcFiles does not appear in the drop down list, and if I type it in manually, an error dialog appears.  In order to have Visual Studio Build Action support, an ItemGroup with AvailableItemName set to include RazorSrcFiles must be declared in either the root project or an included project.  As of now, I have this declared in my root project (so that if I upgrade the nuget package and this isn't added, I don't have to add it again), but this does cause a missing file icon (a minor annoyance, but doesn't cause any actual problems).

**Comment by pranavkm** [comment]
>  In order to have Visual Studio Build Action support, an ItemGroup with AvailableItemName set to include RazorSrcFiles must be declared 

Ahh, didn't know something that like existed. Would adding it to RazorGenerator.MsBuild (since it's an included project) work?

**Comment by TheJayMann** [comment]
Yes, that would be preferable.

**Comment by pranavkm** [comment]
Sorry for the super long delay in getting your PR in. Merged as part of https://github.com/RazorGenerator/RazorGenerator/commit/cb152b60abe0ec0a87074c18b5289bb7750cae00
