### ISSUE TITLE
Add [ExcludeFromCodeCoverage] attribute

### ISSUE THREAD

**Issue by tiesvanraak** [RazorGenerator/RazorGenerator#49]
Hi,

Is there a way to let RazorGenerator add [ExcludeFromCodeCoverage] attribute to all generated files ?
The generater now influences my code coverage percentages.
I'd like to exclude all razor pages by default.

Thanks !

**Comment by pranavkm** [comment]
Add a file named `razorgenerator.directives` to your Views directory with the following content:

`ExcludeFromCodeCoverage: true`

**Comment by davidebbo** [comment]
Didn't know about that one, and it's not listed in https://github.com/RazorGenerator/RazorGenerator/blob/master/README.md. Can you add it?

**Comment by pranavkm** [comment]
Done.
