### ISSUE TITLE
System.Web.Mvc and System.Web.WebPages should be specified in nuspec file as package dedendencies, not as framework dependencies

### ISSUE THREAD

**Issue by Kiryushin-Andrey** [RazorGenerator/RazorGenerator#5]
These two assemblies are not actually a part of .NET framework. They are distributed as nuget packages, so the RazorGenerator.Mvc package should specify them in <dependencies> section with the corresponding packages' versions.

**Comment by davidebbo** [comment]
@pranavkm do you remember how it ended up being this way? When we build RazorGenerator.Mvc, we do have nuget dependencies on Microsoft.AspNet.Mvc and Microsoft.AspNet.WebPages, so it would seem that the nuspec should reflect that.

**Comment by pranavkm** [comment]
I looked up the file's history and it's always been this way. Perhaps we were incorrectly relying on Mvc being in the GAC which isn't true as of Mvc 4. Should be safe to make it a package reference once we test that it works.

**Comment by romansp** [comment]
Let's give some love to [RazorGenerator.Mvc.nuspec](https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Mvc/RazorGenerator.Mvc.nuspec) and [RazorGenerator.Testing.nuspec](https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Testing/RazorGenerator.Testing.nuspec) files. 
I haven't tested yet, but I guess references to ``System.Web.Mvc`` and ``System.Web.WebPages`` should be removed from ``frameworkAssemblies`` section and added as nuget packages instead.

This causes another issue, e.g. https://github.com/fsprojects/Paket/issues/1338, as references are being resolved incorrectly.

I will add PR fixing those later.

**Comment by davidebbo** [comment]
@romansp sounds good. Thanks for offering to address.
