### ISSUE TITLE
Razor Generator generated classes not used by MVC

### ISSUE THREAD

**Issue by RemiBou** [RazorGenerator/RazorGenerator#53]
![dottraceissuemsbuildrazor](https://cloud.githubusercontent.com/assets/1358970/10760825/c80454c6-7cbe-11e5-8936-e8d646f3aa68.PNG)
![dotpeekissuemsbuildrazor](https://cloud.githubusercontent.com/assets/1358970/10760824/c7ff7ca8-7cbe-11e5-821e-afdfd4e8972b.PNG)

Hi

I installed razorgenerator.msbuild on my project. The view's classes are generated as you can see on my screenshot of dotPeek (decompiler) : "ASP._Views...._cshtml' is on the assembly.

But if I dottrace my app, I can see that the pages are recompiled, and the used view class are not the same as the generated ones "ASP.Page_Views....cshtml"

Is there any way to avoid this double generation ?

**Comment by pranavkm** [comment]
Do you have `RazorGenerator.Mvc` installed?

**Comment by RemiBou** [comment]
I have MiniProfiler.MVC4 installed

**Comment by RemiBou** [comment]
Nope it is not

**Comment by pranavkm** [comment]
You'll need the view engine too to prevent the default view engine from compiling views on disk.

**Comment by RemiBou** [comment]
Why is this package not added to the dependencies ?

**Comment by pranavkm** [comment]
You install RazorGenerator.Mvc in the Mvc application and RazorGenerator.MsBuild in the project with cshtml files. They're not necessarily the same (for instance in the case of pluggable areas).
