### ISSUE TITLE
Support for UTF-8 Without Signature (UTF-8 Without BOM)

### ISSUE THREAD

**Issue by monoblaine** [RazorGenerator/RazorGenerator#63]
I've recenly upgraded my projects to VS 2015, and found out that if the `.cshtml` files are encoded with utf-8 without bom, the generated `.cs` files are messed up (The non-ascii characters are replaced with weird equivalents). If I change the encoding to "UTF-8 With Signature" everything is fine. Should I change the encoding of all the files? Or is it something that could be fixed?

(using `RazorGenerator.Mvc`, `v2.3.12`)

**Comment by davidebbo** [comment]
Is that using the VSIX, or the RG.msbuild package?

**Comment by monoblaine** [comment]
I'm not sure whether this is the right answer or not, but it appears that the Visual Studio extension "Razor Generator" is installed. But the NuGet package "RazorGenerator.Mvc" is also installed.

**Comment by monoblaine** [comment]
By the way, this is possibly nothing new and probably not related to Visual Studio 2015 or anything else. The reason I'm having this problem all of a sudden is because I've recently installed an extension named "Fix File Encoding", which prevents Visual Studio from adding BOM to files. Before that, the `.cshtml` files were being saved with BOM by default.

**Comment by davidebbo** [comment]
I did a quick test of a regular MVC project with no RazorGenerator.
- I added some French characters to the view: `éà`. Everything ran fine.
- I then used notepad2 to change the file type to utf8 without BOM. That caused it to get messed up and display `Ã©Ã`.

So it looks like this is general to MVC/Razor, and not anything specific to the RazorGenerator tool.

**Comment by davidebbo** [comment]
Here is the deal. For regular MVC, you can fix it per [this post](http://stackoverflow.com/questions/24431985/how-do-i-make-razor-read-utf-8-files-without-bom), via config:

```xml
<system.web>
    <globalization fileEncoding="utf-8" />
</system.web>
```

But for RZ, we don't have a way to do this today. Relevant code is [here](https://github.com/RazorGenerator/RazorGenerator/blob/a53211bb62ffafac24d7449429936fe713869ad1/RazorGenerator.Core.v2/RazorHost.cs#L137-L140)

```c#
using (var reader = new StreamReader(stream, Encoding.Default, detectEncodingFromByteOrderMarks: true))
{
    results = engine.GenerateCode(reader, className: DefaultClassName, rootNamespace: DefaultNamespace, sourceFileName: _fullPath);
}
```

So it detects the BOM, but falls back to default, which is not UTF8. We could fix it by changing the code to `Encoding.UTF8`, but then any non-UTF-8 would be broken.

I think we need a new RG directive to control that. We need a volunteer to make this happen :)

**Comment by pranavkm** [comment]
Are non-UTF8 schemes terribly common? We could default to UTF8 and wait for folks to complain?

**Comment by davidebbo** [comment]
I guess it's an option. UTF32 (i.e. full Unicode) is probably used by some people. But I can we can be prescriptive and say that utf8 is what you need to use for RG.

**Comment by pranavkm** [comment]
:+1:

**Comment by monoblaine** [comment]
Wow, your comments were all eye-opening, thank you!

If I was the only one having this issue after all this time, leaving it as it is makes sense.

**Comment by davidebbo** [comment]
@monoblaine can you please try http://razorgen-ci.cloudapp.net/repository/download/RazorGenerator_RazorGenerator/104:id/RazorGenerator.vsix and verify that it works as you expect?

**Comment by monoblaine** [comment]
Yes, it works with or without BOM perfectly fine. (I just had to update WebActivatorEx to v2.1.0 because there was something wrong with IntelliSense)

**Comment by davidebbo** [comment]
Pushed to gallery.
