### ISSUE TITLE
Use RazorGenerator for Templated Strings

### ISSUE THREAD

**Issue by TonyValenti** [RazorGenerator/RazorGenerator#64]
Good morning @davidebbo and @pruiz :
I've got a feature request for RazorGenerator:

Right now it has two generators: WebPages and MVC.  I would like a third generator: Text/String Generator.

I would like to be able to write code like this:

````
var Model = new TemplateModel { FirstName = "Tony", LastName = "Valenti};

string Text = MyApp.Templates.SayHello.Execute(Model); //Calling a static Execute<T> Method that outputs a string

MyApp.Templates.SayHello.Execute(Model, new TextWriter()); //Calling a static Execute<T> Method that accepts the text writer.
````

This would essentially allow me to create "templated resources" for complex strings (such as email templates) that I can use.

**Comment by davidebbo** [comment]
This is supported by the generator type 'template'. See https://github.com/davidebbo-test/RazorGeneratorSimpleTemplate for example.
