### ISSUE TITLE
MvcHelper doesn't generate static classes

### ISSUE THREAD

**Issue by MarcWils** [RazorGenerator/RazorGenerator#67]
RazorGenerator doesn't create a static class when the generator type is set to 'MvcHelper'. According to the quick start guide (https://github.com/RazorGenerator/RazorGenerator/wiki/Quick-Start-Guide) this should generate a static class.

This used to work in 1.7 but is broken in >= 1.9. Also tested in 1.10.1.

**Comment by pranavkm** [comment]
There was a change between Mvc 3 -> Mvc 4 where the HelperPage type was modified to derive from a base type. Did you update the Mvc you were targeting whilst you were updating RazorGenerator?

See http://razorgenerator.codeplex.com/workitem/89 for some discussion around this.

**Comment by slothje** [comment]
We used Mvc4 all the time, so while staying on the same Mvc version it first worked, and then it broke

**Comment by MarcWils** [comment]
I can reproduce this issue by creating a new ASP.NET MVC (4 or 5) application in VS2012. The sample from the Quick Start Guide doesn't compile.

```
@* Generator : MvcHelper *@

@helper WriteSpan(this HtmlHelper helper, string text) {
    <span>@text</span>
}
```

**Comment by davidebbo** [comment]
Yes, it does look like something is broken. Here is my test project: https://github.com/davidebbo-test/RazorGeneratorMvc51. As it stands, the app was generated with an old version of the adding. and the helper looks like [this](https://github.com/davidebbo-test/RazorGeneratorMvc51/blob/01e33a02eae6f694d44e29d8f267a59b30d345fd/RazorGeneratorMvc5/Views/Helpers/ListHelper.generated.cs), using a static class.

But after regening it using latest VSIX, it looks like [this](https://github.com/davidebbo-test/RazorGeneratorMvc51/blob/7f1f9298db120a187397f464ed6dc107cd114cdb/RazorGeneratorMvc5/Views/Helpers/ListHelper.generated.cs), with a non-static class that tries to use an extension method (not valid):

```c#
    public class ListHelper : System.Web.WebPages.HelperPage
    {
        public static System.Web.WebPages.HelperResult WriteList(this HtmlHelper helper, IEnumerable<string> list) {
            //...
        }
    }
```

@pranavkm what do you make of this?

**Comment by pranavkm** [comment]
It looks like your application is targeting Mvc 5. They changed the implementation to have helper pages depend on instance state in Mvc4+ (something about the `WriteAttribute` method). We fixed it based on the issue filed in http://razorgenerator.codeplex.com/workitem/89.

**Comment by davidebbo** [comment]
@pranavkm not sure I follow. Right now, it's generating code that is not valid (doesn't compile). What's the way to make it work? Is that not a RG bug?

**Comment by pranavkm** [comment]
I can look at this again, but my guess is our premise is incorrect. I don't think you can use MvcHelper to create extension methods as of Mvc4+. The example used to work in the past because Mvc 3 did not require a base type (had no instance state) and so we were able to produce a static type.

**Comment by davidebbo** [comment]
Actually, this works fine. You just need to tweak the helper and the way you call it. This really isn't RG specific, but is just a general change in how MVC helpers work. See [this commit](https://github.com/davidebbo-test/RazorGeneratorMvc51/commit/5d4c33f0ceaa777dbc5d70fcaebad2d259b9f22b) for details of what you need to change.

**Comment by truongngoctuan** [comment]
the same issue happens to me, but use your work will just make my helper is not intuitive because I built it as a basis helper to be used in other applications
