### ISSUE TITLE
Partial Views to render CSS and JS Files 

### ISSUE THREAD

**Issue by Santhoshsanz** [RazorGenerator/RazorGenerator#68]
I have made a separate library by razor generator tool and getting the dll files. and i referred those dll's in my main MVC project but, i am facing the issue with refereeing the ".css and .js files" in my view, those style-sheets and java-scripts files are not working,can you please help me to solve those issue to manage my .css/.js files.

**Comment by davidebbo** [comment]
Generally, RazorGenerator is about precompiling views, and does nothing related to static files (which are unrelated to Razor). You'll need to make sure that the relevant static files are available on your server.

**Comment by hoghweed** [comment]
Hi, I'm really sad about an anwer like that, I understood RazorGenerator is all about Razor but if I could make separate view assembly, anyone has handled how to make a library with views and scripts and css ??

So saying that, I can have a library of views but these views tight depends on the main app scripts and css, so this library of views is an "half-solution"..

**Comment by bartcoppens** [comment]
@hoghweed FYI: second part of the solution (copying css and js from a shared library) can be achieved using this solution: https://github.com/mcintyre321/EmbeddedResourceVirtualPathProvider
