### ISSUE TITLE
RazorGenerator 1.10 generated C# incompatible with view unit tests

### ISSUE THREAD

**Issue by mithilap13** [RazorGenerator/RazorGenerator#71]
Hi,

We've been using RazorGenerator 1.6 for development of our ViewHelper cshtml files. I tried out 1.10 and am seeing two issues alternately with 1.10:
1. Right after installing 1.10 (and restarting VS), if I modify the ViewHelper cshtml file, the corresponding generated.cs file gets deleted.
2. At other times, right after installing 1.10 (and restarting VS), if I modify the ViewHelper file, the generated C# class ends up being a derivative of HelperPage class with a whole lot of changes in the entire file (not just the portion I modified). The generated code seems to work fine when I run the code through local IIS however, I have some pre-written view unit tests that don't work with this new generated code. The error thrown by the unit test is as follows:

System.Web.WebPages.HelperPage.get_CurrentPage()
System.Web.WebPages.HelperPage.WriteAttributeTo(TextWriter writer, String name, PositionTagged`1 prefix, PositionTagged`1 suffix, AttributeValue[] values)
Helpers.ViewHelpers.HeadlinesViewHelper.<>c__DisplayClass11.<RenderGalleryHeadline>b__10(TextWriter __razor_helper_writer) in 
Helpers.ViewHelpers.GalleryViewHelper.<>c__DisplayClass33.<RenderAdditionalGallery>b__32(TextWriter __razor_helper_writer) in 
System.Web.WebPages.HelperResult.ToString()
Tests.ViewHelpers.GalleryViewHelperTests.VerifyEndlSlateIsNotEmptyWhenConfigKeyIsTrue() in

**Comment by andrewvk** [comment]
Confirmed. It's seems like 1.10 ignores Generator : MvcHelper directive and generates WebPageView instead.

**Comment by davidebbo** [comment]
Not seeing this in my test app https://github.com/davidebbo-test/RazorGeneratorMvc51. e.g. I added `@* Generator : MvcHelper *@` at the top of `About.cshtml`, and the generated code changed from `WebViewPage` to `HelperPage`. That's with RG VSIX 1.10.1.

Does it repro for you with my test app?

**Comment by andrewvk** [comment]
I haven't small repro, but this happens when helper contains WriteAttributeTo call, and helper itself calling from old aspx page (or test environment like in top message).
WriteAttributeTo use HelperPage.CurrentPage. Inside accessor of this property there is a call to HelperPage.PageContext that created from WebPageContext.Current. And WebPageContext.Current is null.

**Comment by andrewvk** [comment]
Temporary workaround - avoid WriteAttributeTo, i.e. code like this:
```
<a href="@href">...
```

**Comment by cezarypiatek** [comment]
Same happend to me. Directive @* Generator : MvcHelper *@ is ignored and RazorGenerator generates class inherited from System.Web.WebPages.HelperPage. It breaks all my helpers. Please fix this issue and update release note. I'm not able to continue my development without that fix.

**Comment by davidebbo** [comment]
@cezarypiatek please see my previous comment.

**Comment by cezarypiatek** [comment]
I read your comment, but RG VSIX 1.9 was generating static class which inherit from nothing. Now when I'm rendering something inside html attribute (case described by @andrewvk ) I've got null reference exception. Sample code that demonstrate that issue:
```
@helper RenderSomething(string id)
{
  <div id="@id">Hello</div>
}
```

**Comment by davidebbo** [comment]
Can we start with the **question** in my comment about whether it repros for you with the test app I point to? Then we can take it from there.

**Comment by cezarypiatek** [comment]
Yes, I was able to reproduce issue using your sample project. I added sample helper into ListHelper.cshtml

```
@helper SampleEmptyList(string id)
{
    <ul id="@(id)"></ul>
}
````

and then I created a UT that reproduce that issue

```
[TestMethod]
public void TestAttributeWrite()
{
    var id = "Test";
    var helperResult = ListHelper.SampleEmptyList(id);
    Assert.IsNotNull(helperResult);
    var stringResult = helperResult.ToString(); //throws NullReferenceException
    Assert.IsNotNull(stringResult);
}
```

**Comment by davidebbo** [comment]
I don't think what you describe is the same as what started this thread. From @andrewvk above:

> It's seems like 1.10 ignores Generator : MvcHelper directive and generates WebPageView instead

I can't repro that, as in my sample the helper class extends `HelperPage`, and not `WebPageView`. But you seem to *not* want it to generate a `HelperPage`, which sounds like the reverse.

In any case, your `SampleEmptyList` helper works fine when used from a page. e.g. try adding `@ListHelper.SampleEmptyList("foo")` to Index.cshtml. It runs and renders exactly as expected.

As for the unit test support, it has always been very experimental, and has not been well maintained. It's likely broken in all kind of ways, and would need someone to drive fixing it. But in any case, that is not related to this discussion.

Closing this issue until I see something that actually looks broken :)
