### ISSUE TITLE
Visual Studio 2015 compatible?

### ISSUE THREAD

**Issue by wallace740** [RazorGenerator/RazorGenerator#75]
I would love to use this extension but I could not find Custom Tool anywhere in the properties window

in the properties window there is no Custom tool, I see only Full Path and File Name nothing more. 
is this compatible with Visual Studio 15?

**Comment by pranavkm** [comment]
Have you installed the extension in VS - https://visualstudiogallery.msdn.microsoft.com/1f6ec6ff-e89b-4c47-8e79-d2d68df894ec?

**Comment by wallace740** [comment]
We already installed the extension but our problem is unable to use that one.

> -Go to an MVC Razor view's property and set the Custom Tool to RazorGenerator
We cannot find the Custom Tool in the properties window.

My question is : Are there anyone using Visual Studio 2015 and able to use this extension?

**Comment by davidebbo** [comment]
Here is what the properties look like in VS 2015:
![image](https://cloud.githubusercontent.com/assets/556238/13290857/55de8d84-daca-11e5-8c55-dcbffeb97db1.png)

If you are not seeing this, either you'r VS is generally very busted, or you are trying this on an ASP.NET 5 project, which is a completely different beast and is not supported.
