### ISSUE TITLE
How to create pre-compiled view for the MVC6?

### ISSUE THREAD

**Issue by AshishMoradiya** [RazorGenerator/RazorGenerator#79]
Hello,

I am able to generate pre-compiled view for MVC5 project template, using technic provided in [this](http://blog.davidebbo.com/2011/06/precompile-your-mvc-views-using.html) URL. I need way to pre-compile views for MVC6 project template. can anybody provide me suggestion to achieve it.

Note: I have already seen [this](https://github.com/RazorGenerator/RazorGenerator/issues/19). but could not find solution.

Regards,
Ashish

**Comment by pranavkm** [comment]
Sorry, there's none at this point that we are working on. The plan is for MVC Core to have official support for it, but that's unlikely to happen until after RTM.
