### ISSUE TITLE
Exemple of RazorGenerator.Test

### ISSUE THREAD

**Issue by Uterr** [RazorGenerator/RazorGenerator#81]
Hello. I found single example for how using RazorGenerator.Test:
http://blog.davidebbo.com/2011/06/unit-test-your-mvc-views-using-razor.html
but example is obsolete (there is no function view.RenderAsHtml(); to be precise), and dont work for current version. Please, can you lead to working example? Thank you

**Comment by davidebbo** [comment]
See https://github.com/davidebbo-test/RazorGeneratorMvc51/blob/master/RazorGeneratorMvc5.Tests/ViewsTests.cs for basic sample. But generally, the whole test thing never got past experimental stage, so expect roughness.

**Comment by Uterr** [comment]
I found what was wrong checking sourse code. In example 
http://blog.davidebbo.com/2011/06/unit-test-your-mvc-views-using-razor.html code only using this:
using RazorGenerator.Testing;

but to make code work, you alse need to do:
using RazorGenerator;
