### ISSUE TITLE
Support razor engine v4

### ISSUE THREAD

**Issue by mariusGundersen** [RazorGenerator/RazorGenerator#86]
It would be really nice to have support for async/await in the compiled razor templates. This is supported in the 4th version of the razor engine by [microsoft](https://github.com/aspnet/Razor) and the [open source implementation](https://github.com/Antaris/RazorEngine).

**Comment by pranavkm** [comment]
The AspNetCore implementations of Razor are different from the AspNet ones. We do not plan on targeting those with this tool.
