### ISSUE TITLE
MVC pageBaseType in ~/Views/Web.config no longer respected

### ISSUE THREAD

**Issue by webwizgordon** [RazorGenerator/RazorGenerator#92]
The new feature for specifying **BaseType** in *razorgenerator.directives* seems to have broken support for recognizing the pageBaseType specified in the *~/Views/Web.config.* 

Example:
```xml
<system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
    <pages pageBaseType="MyNamespace.MyCustomWebViewPage">
</system.web.webPages.razor>
```

If a **BaseType** value is not specified in *razorgenerator.directives*, `System.Web.Mvc.WebViewPage` is always used, ignoring the *Web.Config* value of `MyNamespace.MyCustomWebViewPage`.  
  
I think that if the *razorgenerator.directives* **BaseType** value is not supplied, the expected behavior would be to use the *Web.Config* value instead falling back all the way to `System.Web.Mvc.WebViewPage`.

**Comment by davidebbo** [comment]
@gamulka, this relates to #89. Maybe the fallback logic is not quite right?

**Comment by gamulka** [comment]
@davidebbo Yes, we will check it out.

**Comment by davidebbo** [comment]
Should be fixed in RazorGenerator.MsBuild 2.4.4. @webwizgordon can you verify?

**Comment by webwizgordon** [comment]
_Web.config_ value is respected so it's working great for me again.

I'm not sure if having a **BaseType** in _razorgenerator.directives_ is supposed to override _Web.config_ or not, but it appears **BaseType** in _razorgenerator.directives_ is completely ignored if a `pageBaseType `is provided in _Web.config_. Not a problem for me but I'm not sure if that's the intended design or if precedence is supposed to be _razorgenerator.directives_ **BaseType** > _Web.config_ `pageBaseType` > `System.Web.Mvc.WebViewPage`.
