### ISSUE TITLE
Markup sometimes contains extra period characters at random locations

### ISSUE THREAD

**Issue by aaron-horst** [RazorGenerator/RazorGenerator#95]
Looking for some feedback and possible workarounds for an issue I am noticing with the generator. Occasionally extra periods get ommitted in the markup at various spots. For example a phone number will show up as 800**..**555.5555 (rather than 800.555.5555), images will have an extra dot in front of the resource extensions, hyperlinks will have an extra period after the www. (displayed as www**..**).  It seems completely random and at different locations. Any suggestions on ways to remedy this?

**Comment by pranavkm** [comment]
Does this reproduce without the generator?

**Comment by aaron-horst** [comment]
For example if I serve it up by a classic MVC action with the same model? If so it looks perfect there.

**Comment by aaron-horst** [comment]
Looking at it in a hex editor it definitively is an extra period and not some other character

**Comment by aaron-horst** [comment]
Sorry, I posted to the incorrect project, closing out sorry for the false alarm
