### ISSUE TITLE
Generated class visibility

### ISSUE THREAD

**Issue by MarkPflug** [RazorGenerator/RazorGenerator#96]
Is there a way to control the visibility of the generated classes? I have some razor templates that I want to use in my application, but they don't need to be publicly visible; I'd like to make them internal, but don't see a way to do that.

**Comment by pranavkm** [comment]
@MarkPflug I just added ths to our docs: https://github.com/RazorGenerator/RazorGenerator/blob/master/README.md#changing-type-visiblity

**Comment by MarkPflug** [comment]
Thank you so much for the quick response!
