### ISSUE TITLE
When running custom tool the .generated.cs file has inconsistent lines endings

### ISSUE THREAD

**Issue by StiiCeva** [RazorGenerator/RazorGenerator#98]
I'm using Visual Studio 2012 and after I run the tool using right click run custom tool, I receive the inconsisten lines endings warning and after that nothing works! It doesn't recognize Telerik. :( 

Please help!

**Comment by davidebbo** [comment]
Inconsistent line endings are usually harmless. What specific errors are you getting? Also, to test if it's specific to your repo, can you try with https://github.com/davidebbo-test/RazorGeneratorMvc51? Do you get the same issue?

**Comment by Jehoel** [comment]
It is possible your original `.cshtml` files are using `\n` line-endings but the RazorGenerator generated files are using `\r\n`? (I wish VS would show line-ending types)

**Comment by StiiCeva** [comment]
closing issue as it is very old and new versions of VS seem to warn you about such things (plus, now it is integrated with git)
